In [159]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt # graphs plotting
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline
import numpy
import csv 

from matplotlib import rc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean


from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

import statistics

from wordcloud import WordCloud, STOPWORDS
from itertools import chain
from random import randint
import random

import statistics

from sklearn.cluster import KMeans

from sklearn.datasets import load_digits
from sklearn.decomposition import KernelPCA

import math
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import confusion_matrix

from sklearn.metrics import f1_score


# for Arial typefont
matplotlib.rcParams['font.family'] = 'Arial'


## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("Packages imported")

Packages imported


In [160]:
path = "D:/University/RA/covid_origin/Dataset/variant/"

file_name = "spikeprot0702"
input_file_name = path + file_name + ".fasta"

# file_name = "msa_0223"
# input_file_name = "msa_0223.fasta"

# The fasta defline (name of a sequence) has the following format:
# Strain Name | Accession Number | Host Species | Virus Species) 
sequences_dictionary = {sequence.id : sequence.seq for sequence in SeqIO.parse(input_file_name,'fasta')}

print("Data Loaded")

Data Loaded


In [ ]:
(sequences_dictionary)
# key value pairs
for i in sequences_dictionary:
    aa = sequences_dictionary[i]
    aaa = aa.split('|')
    print(i,aaa[0])

In [161]:

path = "D:/University/RA/covid_origin/Dataset/variant/"

file_name = "variant_surveillance"
input_file_name = path + file_name + ".tsv"

data_variant = pd.read_csv (input_file_name, sep = '\t')

C:\Users\sali85\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6,11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [162]:
deflines = [entry for entry in sequences_dictionary.keys()]             # create a list of deflines
protein_sequences = [entry for entry in sequences_dictionary.values()]  # create a list of protein sequences 

In [163]:
data_variant_1 = (data_variant.loc[:,["Accession ID","Pango lineage","Type","Host"]])
data_variant_1

Accession ID Pango lineage             Type   Host
0         EPI_ISL_426900           B.1  betacoronavirus  Human
1         EPI_ISL_426901           B.1  betacoronavirus  Human
2         EPI_ISL_426902          B.40  betacoronavirus  Human
3         EPI_ISL_426903         B.1.8  betacoronavirus  Human
4         EPI_ISL_426904         B.1.8  betacoronavirus  Human
...                  ...           ...              ...    ...
2201237  EPI_ISL_2790546       B.1.1.7  betacoronavirus  Human
2201238  EPI_ISL_2790547       B.1.1.7  betacoronavirus  Human
2201239  EPI_ISL_2790548       B.1.1.7  betacoronavirus  Human
2201240  EPI_ISL_2790549       B.1.351  betacoronavirus  Human
2201241  EPI_ISL_2790550       B.1.351  betacoronavirus  Human

[2201242 rows x 4 columns]

# Check for Missing values and remove the

In [156]:
# missing_val_check = []
# for i in range(0, len(deflines)):
#     length_check = len(deflines[i])
#     if length_check<50:
#         print(i,', Length = ', len(deflines[i]))
#         missing_val_check.append(i)

82 , Length =  19
287 , Length =  22
363 , Length =  18
422 , Length =  19
456 , Length =  19
1868 , Length =  19
2387 , Length =  28
2408 , Length =  18
2665 , Length =  19
2977 , Length =  17
4148 , Length =  21
4898 , Length =  24
4969 , Length =  20
5151 , Length =  22
10605 , Length =  17
11291 , Length =  20
18850 , Length =  23
20739 , Length =  20
20846 , Length =  20
27599 , Length =  19
30183 , Length =  21
33795 , Length =  18
76592 , Length =  30
77603 , Length =  24
84555 , Length =  31
103413 , Length =  30
114364 , Length =  23
118547 , Length =  30
124853 , Length =  30
145728 , Length =  30
164905 , Length =  19
223630 , Length =  27
260276 , Length =  29
266536 , Length =  23
311197 , Length =  27
314411 , Length =  25
373320 , Length =  22
426807 , Length =  31
529335 , Length =  30
652572 , Length =  28
742907 , Length =  33
752957 , Length =  27
764581 , Length =  29
820770 , Length =  41
838816 , Length =  28
844986 , Length =  24
876857 , Length =  27
904560 , Le

In [157]:
# #removing missing values rows
# for i in range(0, len(missing_val_check)):
#     deflines.remove(deflines[missing_val_check[i]-i])
#     protein_sequences.remove(protein_sequences[missing_val_check[i]-i])
# #     targets.remove(targets[missing_val_check[i]-i])

In [164]:
variant_id = []
variant_name = []
variant_host_name = []
# variant_name_full = []
for tt in range(len(data_variant_1)):
    variant_tmp = data_variant_1.iloc[tt]
    variant_id.append(variant_tmp[0])
    variant_name.append(variant_tmp[1])
    variant_host_name.append(variant_tmp[3])

In [165]:
idx = pd.Index(variant_host_name) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 2201242 entries in total
Human                                  2199147
Environment                                997
Neovison vison                             944
Felis catus                                 48
Canis lupus familiaris                      29
Panthera leo                                24
Manis javanica                              19
Panthera tigris jacksoni                     7
Rhinolophus malayanus                        5
Mus musculus                                 3
Gorilla gorilla gorilla                      3
Mesocricetus auratus                         2
Mustela putorius furo                        2
Rhinolophus shameli                          2
Rhinolophus stheno                           2
Chlorocebus sabaeus                          1
Manis pentadactyla                           1
Mus musculus (BALB/c mice)                   1
Rhinolophus pusillus                         1
Prionailurus bengalensis eupti

In [200]:
tmp_host_name = []
for i in range(0, len(deflines)):
#     print("i = ",i,"/",len(deflines))
    aqw = deflines[i].split('|')
    if(len(deflines[i].split("|"))>=7):
        tmp_host_name.append(aqw[6])
#     else:
#         print(deflines[i])
        if(aqw[6]=='Environment'):
            print(deflines[i])

Spike|hCoV-19/env/Austria/CeMM7723/2021|2021-04-07|EPI_ISL_1840976|Original|hCoV-19^^Vorarlberg|Environment|Department
Spike|hCoV-19/env/Austria/CeMM8899/2021|2021-04-28|EPI_ISL_2232969|Original|hCoV-19^^Carinthia|Environment|Department
Spike|hCoV-19/env/Liaoning/Dalian-IVDC-1/2020|2020-08-27|EPI_ISL_2170885|Original|hCoV-19^^Liaoning|Environment|National
Spike|hCoV-19/env/Austria/CeMM8897/2021|2021-05-02|EPI_ISL_2232968|Original|hCoV-19^^Austria|Environment|Department
Spike|hCoV-19/env/Austria/CeMM8358/2021|2021-04-25|EPI_ISL_2137174|Original|hCoV-19^^Vorarlberg|Environment|Department
Spike|hCoV-19/env/Austria/CeMM8865/2021|2021-05-05|EPI_ISL_2232950|Original|hCoV-19^^Vienna|Environment|Institute
Spike|hCoV-19/env/Austria/CeMM7736/2021|2021-04-01|EPI_ISL_1840986|Original|hCoV-19^^Salzburg|Environment|Department
Spike|hCoV-19/env/Austria/CeMM8138/2021|2021-04-13|EPI_ISL_1965670|Original|hCoV-19^^Tyrol|Environment|Institute
Spike|hCoV-19/env/Austria/CeMM7230/2021|2021-04-01|EPI_ISL_1671

In [172]:
idx = pd.Index(tmp_host_name) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 1794594 entries in total
Human          1792934
Neovison           931
Environment        627
Felis               33
Manis               19
Panthera            19
Canis               15
Rhinolophus         10
Mustela              2
Canine               1
Mus                  1
Chlorocebus          1
Gorilla              1
dtype: int64


In [ ]:
len(protein_s1)

In [ ]:
deflines_red = []
for i in range(0, len(deflines)):
#     print("i = ",i,"/",len(deflines))
    aqw = deflines[i].split('|')
    if(len(deflines[i].split("|"))>=7):
#         if(len(protein_sequences[i])==1274):
        if(aqw[6]=='Environment'):
            deflines_red.append(deflines[i])

In [ ]:
deflines_red

In [ ]:
deflines_red2 = []
for i in range(0, len(deflines)):
#     print("i = ",i,"/",len(deflines))
    aqw = deflines[i].split('|')
    if(len(deflines[i].split("|"))>=7):
#         if(len(protein_sequences[i])==1274):
        if(aqw[6]=='Panthera'):
            deflines_red2.append(deflines[i])
            
deflines_red2

In [179]:
total_rand_nums = 10
random_int_vals = random.sample(range(0, 30000), total_rand_nums)
random_int_vals.sort()
random_int_vals

[2141, 3494, 6603, 10216, 12075, 15930, 15992, 26561, 27110, 28376]

In [184]:
cities = []
protein_sequences_old = []
deflines_old = []
variant_lst = []

city_names_only = []
# city_name_orig_save_2 = []

total_rand_nums = 1500
random_int_vals = random.sample(range(0, 30000), total_rand_nums)
random_int_vals.sort()

counter = 1
counter_2 = 0
for i in range(0, len(deflines)):
#     print("i = ",i,"/",len(deflines))
    aqw = deflines[i].split('|')
    if(len(deflines[i].split("|"))>=7):
#         if(len(protein_sequences[i])==1274):
        if(aqw[6]=='Human'):
            if(counter<total_rand_nums and random_int_vals[counter]==counter_2): #get random human sequences
                tmp_cariant = (deflines[i].split("|")[3])
                find_variant_index = [ir for ir, nb in enumerate(variant_id) if nb == tmp_cariant] # List comprehension
                if(len(find_variant_index)>0): 
                    if(variant_name[find_variant_index[0]]!='nan'):
                        if(variant_name[find_variant_index[0]]!='None'):
                            print("counter = ",counter)
                            counter = counter+1

                            variant_lst.append(variant_name[find_variant_index[0]])


                            aaa = (deflines[i].split("|")[1])
                            aaaa = aaa.split("/")[1]

                            cities.append(aaaa)
                            protein_s1 = protein_sequences[i]
#                                 protein_sequences_old.append(protein_s1[14:686])  # S1 spike protein
                            protein_sequences_old.append(protein_s1)  # S1 spike protein
                            deflines_old.append(deflines[i])

                            temp = aqw[5]
                            temp2 = temp.split('^')
                            temp3 = temp2[2]

                            city_names_only.append(temp3)
            else:
                counter_2 = counter_2+1
                        
        else:
#             if(len(protein_sequences[i])==1274):
            tmp_cariant = (deflines[i].split("|")[3])
            find_variant_index = [ir for ir, nb in enumerate(variant_id) if nb == tmp_cariant] # List comprehension
            if(len(find_variant_index)>0): 
                if(variant_name[find_variant_index[0]]!='nan'):
                    if(variant_name[find_variant_index[0]]!='None'):
#                         print("counter = ",counter)
#                         counter = counter+1

                        variant_lst.append(variant_name[find_variant_index[0]])


                        aaa = (deflines[i].split("|")[1])
                        aaaa = aaa.split("/")[1]

                        cities.append(aaaa)
                        protein_s1 = protein_sequences[i]
                        protein_sequences_old.append(protein_s1)  # S1 spike protein
                        deflines_old.append(deflines[i])

                        temp = aqw[5]
                        temp2 = temp.split('^')
                        temp3 = temp2[2]

                        city_names_only.append(temp3)
            
            


# protein_sequences = protein_sequences_old
print(cities)

counter =  1
counter =  2
counter =  3
counter =  4
counter =  5
counter =  6
counter =  7
counter =  8
counter =  9
counter =  10
counter =  11
counter =  12
counter =  13
counter =  14
counter =  15
counter =  16
counter =  17
counter =  18
counter =  19
counter =  20
counter =  21
counter =  22
counter =  23
counter =  24
counter =  25
counter =  26
counter =  27
counter =  28
counter =  29
counter =  30
counter =  31
counter =  32
counter =  33
counter =  34
counter =  35
counter =  36
counter =  37
counter =  38
counter =  39
counter =  40
counter =  41
counter =  42
counter =  43
counter =  44
counter =  45
counter =  46
counter =  47
counter =  48
counter =  49
counter =  50
counter =  51
counter =  52
counter =  53
counter =  54
counter =  55
counter =  56
counter =  57
counter =  58
counter =  59
counter =  60
counter =  61
counter =  62
counter =  63
counter =  64
counter =  65
counter =  66
counter =  67
counter =  68
counter =  69
counter =  70
counter =  71
counter =  72
c

In [185]:
(deflines_old)

tmp_host_name_2 = []
for i in range(0, len(deflines_old)):
    aqw = deflines_old[i].split('|')
    if(len(deflines_old[i].split("|"))>=7):
        tmp_host_name_2.append(aqw[6])
#         if(aqw[6]=='Human'):

In [186]:
idx = pd.Index(tmp_host_name_2) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 3065 entries in total
Human          1499
Neovison        931
Environment     561
Felis            30
Panthera         15
Canis            12
Manis             7
Rhinolophus       4
Mustela           2
Chlorocebus       1
Mus               1
Canine            1
Gorilla           1
dtype: int64


In [187]:
final_host_names = []

final_variant_names = []
final_cities = []
final_deflines = []
final_proteins = []

for w in range(len(protein_sequences_old)):
    if(len(protein_sequences_old[w])>0):
        if(tmp_host_name_2[w]=="Human" or tmp_host_name_2[w]=="Neovison" or tmp_host_name_2[w]=="Environment"):
            final_cities.append(cities[w])
            final_deflines.append(deflines_old[w])
            final_proteins.append(protein_sequences_old[w])
            final_host_names.append(tmp_host_name_2[w])

In [225]:
# ofile = open("D:/University/RA/JCB_Viral_Host_Classification/Dataset/my_fasta.fasta", "w")

# from Bio import SeqIO

az = (zip(final_proteins & final_deflines))
# SeqIO.write(az), "D:/University/RA/JCB_Viral_Host_Classification/Dataset/example.fasta", "fasta")


# with open("D:/University/RA/JCB_Viral_Host_Classification/Dataset/example.fasta", "w") as output_handle:
#     SeqIO.write(az, output_handle, "fasta")

TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [198]:
idx = pd.Index(final_host_names) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

Here are all of the viral species in the dataset: 
 2991 entries in total
Human          1499
Neovison        931
Environment     561
dtype: int64


In [188]:
protein_sequences_final = []
for r in range(len(final_proteins)):
    protein_sequences_final.append(list(final_proteins[r]))

In [133]:
len(protein_sequences_final)

2627

In [194]:
len(protein_sequences_final[0])

new_protein_seq = []

for i in range(len(protein_sequences_final)):
    tmp_lst = []
    for j in range(1277):
        tmp_lst.append("X")
    new_protein_seq.append(tmp_lst)

In [195]:
new_protein_seq_2 = []

for i in range(len(protein_sequences_final)):
    tt = protein_sequences_final[i]
    tt_2 = new_protein_seq[i]
    tt_2[0:len(tt)] = tt
    ls = [x if (x!="*") else "X" for x in tt_2]
    new_protein_seq_2.append(ls)
#     new_protein_seq_2[0:len(tt)] = tt

In [197]:
len(new_protein_seq_2)

2991

In [196]:
dataset_save_path = "D:/University/RA/JCB_Viral_Host_Classification/Dataset/"
temp_name_tmp = "second_Final_Host_protein_data"
Trial = 1

with open(dataset_save_path + temp_name_tmp + ".csv", 'w', newline='') as file:
    writer = csv.writer(file)
    for i in range(0,len(new_protein_seq_2)):
        if(len(new_protein_seq_2[i])>0):
            writer.writerow(new_protein_seq_2[i])

In [190]:
dataset_save_path = "D:/University/RA/JCB_Viral_Host_Classification/Dataset/"
temp_name_tmp = "Final_Host_names_data"
Trial = 1

with open(dataset_save_path + temp_name_tmp + ".csv", 'w', newline='') as file:
    writer = csv.writer(file)
    for i in range(0,len(final_host_names)):
        writer.writerow(str(final_host_names[i]))

In [61]:
len(final_host_names)

1009

# Writing Complete Reduced Data

In [74]:
final_variant_names = []
final_cities = []
final_deflines = []
final_proteins = []

for w in range(len(protein_sequences_old)):
    if(len(protein_sequences_final[w])>0):
        if(variant_lst[w]=="B.1.1.7" or variant_lst[w]=="B.1.2" or variant_lst[w]=="P.1" or 
           variant_lst[w]=="B.1.526" or variant_lst[w]=="B.1.617.2" or variant_lst[w]=="B.1.429" or 
           variant_lst[w]=="B.1.351" or variant_lst[w]=="B.1" or variant_lst[w]=="B.1.1.519" or variant_lst[w]=="B.1.427"):
            final_variant_names.append(variant_lst[w])
            final_cities.append(cities[w])
            final_deflines.append(deflines_old[w])
            final_proteins.append(protein_sequences_old[w])

# Here are all of the viral species in the dataset: 
#  8536 entries in total
# B.1.1.7      5626
# B.1.2         261
# P.1           259
# B.1.526       259
# B.1.617.2     186
# B.1.429       170
# B.1.351       133
# B.1           128
# B.1.1.519     112
# B.1.427        76

In [78]:
protein_sequences_final = []
for r in range(len(final_proteins)):
    protein_sequences_final.append(list(final_proteins[r]))

In [79]:
dataset_save_path = "D:/University/RA/covid_origin/Dataset/variant/preprocessed/"
temp_name_tmp = "New_reduced_data"
Trial = 1

with open(dataset_save_path + temp_name_tmp + "_covid_protein_sequences_trial_" + str(Trial) + ".csv", 'w', newline='') as file:
    writer = csv.writer(file)
    for i in range(0,len(protein_sequences_final)):
        if(len(protein_sequences_final[i])>0):
            writer.writerow(protein_sequences_final[i])

In [233]:
len(protein_sequences_final[0])

672

In [84]:
idx = pd.Index(final_variant_names) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

Here are all of the viral species in the dataset: 
 7210 entries in total
B.1.1.7      5626
B.1.2         261
B.1.526       259
P.1           259
B.1.617.2     186
B.1.429       170
B.1.351       133
B.1           128
B.1.1.519     112
B.1.427        76
dtype: int64


# Now run the Java code for Kernel Generation, then run the below code!!!!!!

# Reading kernel matrix

In [226]:
# read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/new_Kernel_k4_m0_Alphabet_Size21_trial_1.txt"
read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/new_Kernel_k6_m3_Alphabet_Size21_trial_1.txt"

seq_file_small = []
with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        seq_file_small.append(', '.join(row))

In [227]:
final_jernel_mat = []
mat_2 = []
for y in range(0,len(seq_file_small)):
    aa = seq_file_small[y].split(" ")
    tmp_list = []
    for yy in range(0,len(aa)-1):
        tmp_list.append(int(aa[yy]))
    
    final_jernel_mat.append(tmp_list)

In [244]:
len(final_jernel_mat[0])

7210

# Agglomerative Clustering

In [229]:
################ Kernel Trick ######################
mat_2 = np.zeros((len(final_jernel_mat),len(final_jernel_mat)))

for i in range(0,len(final_jernel_mat)):
    tmp_2 = final_jernel_mat[i][i]
    for j in range(0,len(final_jernel_mat)):
        denom = math.sqrt(tmp_2 * final_jernel_mat[j][j])
        temp = final_jernel_mat[i][j] / (denom)
#         mat_2[i][j] = 1 - temp
        mat_2[i][j] = final_jernel_mat[i][i] + final_jernel_mat[j][j] - (2*(final_jernel_mat[i][j])) # distance kernel trick
################ Kernel Trick ######################

################ Agglomerative Clustering ######################
model = AgglomerativeClustering(affinity='precomputed', n_clusters=6, linkage='average').fit(mat_2)
# print(model.labels_)
clusters_ids = model.labels_
################ Agglomerative Clustering ######################

# Kernel PCA

In [225]:
#############  Kernel PCA ################
transformer = KernelPCA(n_components=20, kernel='precomputed')
X_transformed = transformer.fit_transform(final_jernel_mat)
X_transformed.shape
#############  Kernel PCA ################

#############  K-Means ################
kmeans = KMeans(n_clusters=5, random_state=0).fit(X_transformed)
clusters_ids = kmeans.labels_
#############  K-Means ################

In [230]:
#############  Confusion Matrix ################

unique_labels = np.unique(final_variant_names)
labels_integers = []
for i in range(len(final_variant_names)):
    aa = (np.where(unique_labels==final_variant_names[i]))
    labels_integers.append(aa[0][0])

# confusion_matrix(clusters_ids,labels_integers)

confuse = confusion_matrix(labels_integers,clusters_ids)

confuse_matrix = []
for i in range(0,len(confuse)):
    confuse_matrix.append(list(confuse[i]))
#############  Confusion Matrix ################
pd.DataFrame(confuse_matrix)

0   1     2    3  4  5  6  7  8  9
0   0   1   119    8  0  0  0  0  0  0
1   0   4    95   13  0  0  0  0  0  0
2  47  95  4882  600  1  1  0  0  0  0
3   3   6   228   24  0  0  0  0  0  0
4   1   3   120    9  0  0  0  0  0  0
5   1   0    68    7  0  0  0  0  0  0
6   2   2   152   14  0  0  0  0  0  0
7   4   8   220   27  0  0  0  0  0  0
8   1   2   155   28  0  0  0  0  0  0
9   3   4   228   24  0  0  0  0  0  0

In [224]:
from sklearn import metrics

def purity_score(y_true, y_pred):
    # compute contingency matrix (also called confusion matrix)
    contingency_matrix = metrics.cluster.contingency_matrix(y_true, y_pred)
    # return purity
    return np.sum(np.amax(contingency_matrix, axis=0)) / np.sum(contingency_matrix) 


# purity_score(labels_integers,clusters_ids)

In [231]:
for qq in range(len(np.unique(clusters_ids))):
    names_holder = []
    for ee in range(len(clusters_ids)):
        if(clusters_ids[ee]==qq):
            names_holder.append(final_variant_names[ee])

    mode_val = statistics.mode(names_holder)
    print("Cluster Name = ",mode_val, ", Cluster ID = ",qq)

#     print("Cluster = ",clusters_ids)
    idx = pd.Index(names_holder) # creates an index which allows counting the entries easily
    print(len(idx),"entries in total")
    aq = (idx.value_counts())
    print(aq,"\n")

Cluster Name =  B.1.1.7 , Cluster ID =  0
62 entries in total
B.1.1.7      47
B.1.526       4
P.1           3
B.1.2         3
B.1.429       2
B.1.617.2     1
B.1.351       1
B.1.427       1
dtype: int64 

Cluster Name =  B.1.1.7 , Cluster ID =  1
125 entries in total
B.1.1.7      95
B.1.526       8
B.1.2         6
B.1.1.519     4
P.1           4
B.1.351       3
B.1.617.2     2
B.1.429       2
B.1           1
dtype: int64 

Cluster Name =  B.1.1.7 , Cluster ID =  2
6267 entries in total
B.1.1.7      4882
P.1           228
B.1.2         228
B.1.526       220
B.1.617.2     155
B.1.429       152
B.1.351       120
B.1           119
B.1.1.519      95
B.1.427        68
dtype: int64 

Cluster Name =  B.1.1.7 , Cluster ID =  3
754 entries in total
B.1.1.7      600
B.1.617.2     28
B.1.526       27
P.1           24
B.1.2         24
B.1.429       14
B.1.1.519     13
B.1.351        9
B.1            8
B.1.427        7
dtype: int64 

Cluster Name =  B.1.1.7 , Cluster ID =  4
1 entries in total
B.1.1

In [166]:
idx = pd.Index(final_variant_names) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

Here are all of the viral species in the dataset: 
 7210 entries in total
B.1.1.7      5626
B.1.2         261
B.1.526       259
P.1           259
B.1.617.2     186
B.1.429       170
B.1.351       133
B.1           128
B.1.1.519     112
B.1.427        76
dtype: int64


In [219]:
cluster_number_tmp = 2
cluster_name_tmp = "B.1.1.7"

names_holder = []
for ee in range(len(clusters_ids)):
    if(clusters_ids[ee]==cluster_number_tmp):
        names_holder.append(final_variant_names[ee])

mode_val = statistics.mode(names_holder)
# print("Cluster Name = ",mode_val, ", Cluster ID = ",qq)

#     print("Cluster = ",clusters_ids)
idx = pd.Index(names_holder) # creates an index which allows counting the entries easily
print(len(idx),"entries in total")
aq = (idx.value_counts())
print(aq,"\n")

#############  Confusion Matrix ################

unique_labels = np.unique(names_holder)
labels_integers = []
for i in range(len(names_holder)):
    aa = (np.where(unique_labels==names_holder[i]))
    labels_integers.append(aa[0][0])

pred_labels = []
for ch in range(len(names_holder)):
    pred_labels.append(cluster_name_tmp)

confuse = confusion_matrix(names_holder,pred_labels)

confuse_matrix = []
for i in range(0,len(confuse)):
    confuse_matrix.append(list(confuse[i]))
#############  Confusion Matrix ################

print("F1 macro",f1_score(names_holder, pred_labels, average='macro'))
print("F1 micro",f1_score(names_holder, pred_labels, average='micro'))
print("F1 weighted",f1_score(names_holder, pred_labels, average='weighted'))

6268 entries in total
B.1.1.7      4881
P.1           229
B.1.2         228
B.1.526       220
B.1.617.2     156
B.1.429       152
B.1.351       120
B.1           119
B.1.1.519      95
B.1.427        68
dtype: int64 

F1 macro 0.08755942236971925
F1 micro 0.778717294192725
F1 weighted 0.6818403646882573


In [213]:
cluster_number_tmp = 2
cluster_name_tmp = "P.1"

names_holder = []
for ee in range(len(clusters_ids)):
    if(clusters_ids[ee]==cluster_number_tmp):
        names_holder.append(final_variant_names[ee])

mode_val = statistics.mode(names_holder)
# print("Cluster Name = ",mode_val, ", Cluster ID = ",qq)

#     print("Cluster = ",clusters_ids)
idx = pd.Index(names_holder) # creates an index which allows counting the entries easily
print(len(idx),"entries in total")
aq = (idx.value_counts())
print(aq,"\n")

#############  Confusion Matrix ################

unique_labels = np.unique(names_holder)
labels_integers = []
for i in range(len(names_holder)):
    aa = (np.where(unique_labels==names_holder[i]))
    labels_integers.append(aa[0][0])

pred_labels = []
for ch in range(len(names_holder)):
    pred_labels.append(cluster_name_tmp)

confuse = confusion_matrix(names_holder,pred_labels)

confuse_matrix = []
for i in range(0,len(confuse)):
    confuse_matrix.append(list(confuse[i]))
#############  Confusion Matrix ################

print("F1 macro",f1_score(names_holder, pred_labels, average='macro'))
print("F1 micro",f1_score(names_holder, pred_labels, average='micro'))
print("F1 weighted",f1_score(names_holder, pred_labels, average='weighted'))

6268 entries in total
B.1.1.7      4881
P.1           229
B.1.2         228
B.1.526       220
B.1.617.2     156
B.1.429       152
B.1.351       120
B.1           119
B.1.1.519      95
B.1.427        68
dtype: int64 

F1 macro 0.007049407418808681
F1 micro 0.03653477983407786
F1 weighted 0.0025754854800689024


# Classification Approach

In [245]:
final_freq_vec = []
flat_list = [item for sublist in protein_sequences_final for item in sublist]

uniqueWords = np.unique(flat_list)
uniqueWords_2 = list(uniqueWords)



In [249]:
uniqueWords

array(['*', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N',
       'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y'], dtype='<U1')

In [250]:
for ind_freq in range(len(protein_sequences_final)):
    print(ind_freq,"/",len(protein_sequences_final))
    temp_freq_vec = [0]* len(uniqueWords)
    aaa = protein_sequences_final[ind_freq]
    for i in range(len(aaa)):
        ind = uniqueWords_2.index(aaa[i])
        temp_freq_vec[ind] = temp_freq_vec[ind] + 1
    final_freq_vec.append(temp_freq_vec)

0 / 7210
1 / 7210
2 / 7210
3 / 7210
4 / 7210
5 / 7210
6 / 7210
7 / 7210
8 / 7210
9 / 7210
10 / 7210
11 / 7210
12 / 7210
13 / 7210
14 / 7210
15 / 7210
16 / 7210
17 / 7210
18 / 7210
19 / 7210
20 / 7210
21 / 7210
22 / 7210
23 / 7210
24 / 7210
25 / 7210
26 / 7210
27 / 7210
28 / 7210
29 / 7210
30 / 7210
31 / 7210
32 / 7210
33 / 7210
34 / 7210
35 / 7210
36 / 7210
37 / 7210
38 / 7210
39 / 7210
40 / 7210
41 / 7210
42 / 7210
43 / 7210
44 / 7210
45 / 7210
46 / 7210
47 / 7210
48 / 7210
49 / 7210
50 / 7210
51 / 7210
52 / 7210
53 / 7210
54 / 7210
55 / 7210
56 / 7210
57 / 7210
58 / 7210
59 / 7210
60 / 7210
61 / 7210
62 / 7210
63 / 7210
64 / 7210
65 / 7210
66 / 7210
67 / 7210
68 / 7210
69 / 7210
70 / 7210
71 / 7210
72 / 7210
73 / 7210
74 / 7210
75 / 7210
76 / 7210
77 / 7210
78 / 7210
79 / 7210
80 / 7210
81 / 7210
82 / 7210
83 / 7210
84 / 7210
85 / 7210
86 / 7210
87 / 7210
88 / 7210
89 / 7210
90 / 7210
91 / 7210
92 / 7210
93 / 7210
94 / 7210
95 / 7210
96 / 7210
97 / 7210
98 / 7210
99 / 7210
100 / 7210

In [265]:
X_train, X_test, y_train, y_test = train_test_split(
    np.array(final_jernel_mat),final_variant_names,
    test_size=0.3,
    random_state=1,
shuffle=True)
# final_freq_vec

In [ ]:
svm_return = svm_fun(X_train,y_train,X_test,y_test)

In [ ]:
svm_table_final_no_DL = DataFrame(svm_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

In [266]:
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

In [261]:
top_k_val = 3
predicted_labels = []

for test_ind in range(len(X_test)):
    temp_dot_prod = []
    for i in range(len(X_train)):
        temp_dot_prod.append(np.dot(X_test[test_ind],X_train[i]))

    top_2_idx = np.argsort(temp_dot_prod)[-top_k_val:] #index of top k values
#     top_2_idx = np.argsort(temp_dot_prod)[:top_k_val] #index of smallest k values
    top_2_values = [temp_dot_prod[i] for i in top_2_idx] #top k values

    train_val_check = [y_train[i] for i in top_2_idx] #label index of top k 
    final_label_check = statistics.mode(train_val_check) #mode label for top k
    predicted_labels.append(final_label_check)

In [262]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):
    #creating a set of all the unique classes using the actual class list
    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc


    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

In [263]:
LR_acc = metrics.accuracy_score(y_test, predicted_labels)
LR_prec = metrics.precision_score(y_test, predicted_labels,average='weighted')
LR_recall = metrics.recall_score(y_test, predicted_labels,average='weighted')
LR_f1_weighted = metrics.f1_score(y_test, predicted_labels,average='weighted')
LR_f1_macro = metrics.f1_score(y_test, predicted_labels,average='macro')
LR_f1_micro = metrics.f1_score(y_test, predicted_labels,average='micro')
macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, predicted_labels, average='macro')

confuse = confusion_matrix(y_test, predicted_labels)
print("Confusion Matrix LR : \n", confuse)
print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))

Confusion Matrix LR : 
 [[   0    0   43    0    0    0    0    0    0    0]
 [   0    0   31    0    0    0    0    0    0    0]
 [   0    0 1676    1    0    0    0    0    0    0]
 [   0    0   77    0    0    0    0    0    0    0]
 [   0    0   47    0    0    0    0    0    0    0]
 [   0    0   29    0    0    0    0    0    0    0]
 [   0    0   51    0    0    0    0    0    0    0]
 [   0    0   71    0    0    0    0    0    0    0]
 [   0    0   51    0    0    0    0    0    0    0]
 [   0    0   86    0    0    0    0    0    0    0]]
LR Class Wise Accuracy :  [0.        0.        0.9994037 0.        0.        0.        0.
 0.        0.        0.       ]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [264]:
check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]

aa = DataFrame(check)
aaa = np.transpose(aa)

final_mat = DataFrame(np.transpose(aa))
final_mat.columns =["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]
final_mat

Accuracy  Precision   Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
0   0.77485   0.601028  0.77485       0.676959    0.087314     0.77485   

    ROC AUC  
0  0.499946