In [146]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
# import matplotlib
# import matplotlib.font_manager
# import matplotlib.pyplot as plt # graphs plotting
# import Bio
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline

from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score


# from matplotlib import rc
# # for Arial typefont
# matplotlib.rcParams['font.family'] = 'Arial'

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean

## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("done")

done


In [165]:
import csv
# read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/new_Kernel_k4_m0_Alphabet_Size21_trial_1.txt"
read_path = "D:/University/RA/JCB_Viral_Host_Classification/Dataset/Final_Host_names_data.csv"

host_names_new = []
with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        host_names_new.append(', '.join(row))

In [148]:
(host_names_new[0])

'Human'

In [174]:
final_labels_temp = [] 
for entry in host_names_new:
    if entry == 'Canis':
        final_labels_temp.append(0)
    elif entry == 'Environment':
        final_labels_temp.append(1)
    elif entry == 'Neovison':
        final_labels_temp.append(2)
    elif entry == 'Human':
        final_labels_temp.append(3)
#     elif entry == 'Neovison':
#         final_labels_temp.append(4)
    elif entry == 'Panthera':
        final_labels_temp.append(4)
        
# final_labels_temp = [] 
# for entry in cities:
#     if entry == 'human_mammal_gb':
#         final_labels_temp.append(1)
#     elif entry == 'camel_mammal_gb':
#         final_labels_temp.append(2)
#     elif entry == 'cat_mammal_gb':
#         final_labels_temp.append(3)
#     elif entry == 'chicken_avian_gb':
#         final_labels_temp.append(4)
#     elif entry == 'bat_mammal_gb':
#         final_labels_temp.append(5)
#     elif entry == 'swine_mammal_gb':
#         final_labels_temp.append(6)
#     else:
#         final_labels_temp.append(0)

In [175]:
idx = pd.Index(final_labels_temp) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

print(np.unique(final_labels_temp))

Here are all of the viral species in the dataset: 
 2991 entries in total
3    1499
2     931
1     561
dtype: int64
[1 2 3]


# Reading kernel matrix

In [168]:
# read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/new_Kernel_k4_m0_Alphabet_Size21_trial_1.txt"
read_path = "D:/University/RA/covid_origin/Code/Kernel_approximation/new2_Kernel_k6_m3_Alphabet_Size21_trial_1.txt"

seq_file_small = []
with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        seq_file_small.append(', '.join(row))

In [169]:
final_jernel_mat = []
mat_2 = []
for y in range(0,len(seq_file_small)):
    aa = seq_file_small[y].split(" ")
    tmp_list = []
    for yy in range(0,len(aa)-1):
        tmp_list.append(int(aa[yy]))
    
    final_jernel_mat.append(tmp_list)

In [176]:
len(final_jernel_mat),len(final_labels_temp)

(2991, 2991)

# Read Protein Data

In [162]:
read_path = "D:/University/RA/JCB_Viral_Host_Classification/Dataset/Final_Host_protein_data.csv"

protein_data_tmp = []
with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        protein_data_tmp.append(', '.join(row))

In [163]:
final_protein_data_tmp = []
mat_2 = []
for y in range(0,len(protein_data_tmp)):
    aa = protein_data_tmp[y].split(",")
    tmp_list = []
    for yy in range(0,len(aa)-1):
        ch = aa[yy]
        ch_1 = ch.replace(" ","")
        tmp_list.append(ch_1)
    
    final_protein_data_tmp.append(tmp_list)

In [156]:
aq = (final_protein_data_tmp[0])
aq[1270:1275]

['H', 'Y', 'T', '', '']

# Classifier Functions

In [177]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc
    
    
    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

def svm_fun_kernel(X_train,y_train,X_test,y_test,kernel_mat):

#     clf = svm.SVC()
    clf = svm.SVC(kernel=kernel_mat)
    
    #Train the model using the training sets
    clf.fit(kernel_mat, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Kernel Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    
# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,NB_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,MLP_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,knn_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,fr_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


def fun_decision_tree(X_train,y_train,X_test,y_test):
    from sklearn import tree
    
    clf = tree.DecisionTreeClassifier()    
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    dt_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    dt_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    dt_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    dt_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    dt_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    dt_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix DT : \n", confuse)
    print("DT Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


In [158]:
len(final_jernel_mat)

2991

# Kernel PCA

In [178]:
from sklearn.decomposition import KernelPCA

#############  Kernel PCA ################
transformer = KernelPCA(n_components=50, kernel='precomputed')
X_transformed = transformer.fit_transform(final_jernel_mat)
X_transformed.shape
#############  Kernel PCA ################

# #############  K-Means ################
# kmeans = KMeans(n_clusters=5, random_state=0).fit(X_transformed)
# clusters_ids = kmeans.labels_
# #############  K-Means ################

(2991, 50)

In [179]:
np.unique(final_labels_temp)

array([1, 2, 3])

In [180]:
X = np.array(final_jernel_mat)
y =  np.array(final_labels_temp)

rkf = RepeatedKFold(n_splits=3, n_repeats=1, random_state=None)
# X is the feature set and y is the target
counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []

for train_index, test_index in rkf.split(X):
    print("Start!!")
    counter = counter+1
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    
    gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
    mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
    knn_return = knn_fun(X_train,y_train,X_test,y_test)
    rf_return = rf_fun(X_train,y_train,X_test,y_test)
    lr_return = lr_fun(X_train,y_train,X_test,y_test)
    dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
#     svm_return = svm_fun(X_train,y_train,X_test,y_test)
#     svm_return = svm_fun_kernel(X_train,y_train,X_test,y_test,final_jernel_mat)

    
    gauu_nb_table.append(gauu_nb_return)
    mlp_table.append(mlp_return)
    knn_table.append(knn_return)
    rf_table.append(rf_return)
    lr_table.append(lr_return)
    dt_table.append(dt_return)
#     svm_table.append(svm_return)
     
# svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Start!!
Confusion Matrix NB : 
 [[ 28 145  17]
 [  6 292   0]
 [ 26 471  12]]
NB Class Wise Accuracy :  [0.14736842 0.97986577 0.02357564]
Confusion Matrix MLP : 
 [[ 23  48 119]
 [  4 271  23]
 [ 22  68 419]]
MLP Class Wise Accuracy :  [0.12105263 0.90939597 0.82318271]
Confusion Matrix KNN : 
 [[ 85  10  95]
 [ 10 248  40]
 [ 31  24 454]]
KNN Class Wise Accuracy :  [0.44736842 0.83221477 0.89194499]
Confusion Matrix RF : 
 [[ 83  26  81]
 [  5 280  13]
 [ 14  15 480]]
RF Class Wise Accuracy :  [0.43684211 0.93959732 0.94302554]
Confusion Matrix LR : 
 [[ 80  34  76]
 [  6 289   3]
 [  9  21 479]]
LR Class Wise Accuracy :  [0.42105263 0.96979866 0.9410609 ]
Confusion Matrix DT : 
 [[ 73  35  82]
 [  7 281  10]
 [ 21  22 466]]
DT Class Wise Accuracy :  [0.38421053 0.94295302 0.91552063]
Start!!
Confusion Matrix NB : 
 [[ 51 141   5]
 [  7 297   2]
 [ 42 450   2]]
NB Class Wise Accuracy :  [0.25888325 0.97058824 0.00404858]
Confusion Matrix MLP : 
 [[ 12  59 126]
 [  0 303   3]
 [ 12  7

C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


Confusion Matrix LR : 
 [[ 96  28  73]
 [  3 299   4]
 [ 18  24 452]]
LR Class Wise Accuracy :  [0.48730964 0.97712418 0.91497976]
Confusion Matrix DT : 
 [[ 90  29  78]
 [ 11 292   3]
 [ 51  30 413]]
DT Class Wise Accuracy :  [0.45685279 0.95424837 0.83603239]
Start!!
Confusion Matrix NB : 
 [[ 43 130   1]
 [ 31 295   1]
 [ 66 425   5]]
NB Class Wise Accuracy :  [0.24712644 0.90214067 0.01008065]
Confusion Matrix MLP : 
 [[ 30  47  97]
 [ 20 291  16]
 [ 23  64 409]]
MLP Class Wise Accuracy :  [0.17241379 0.88990826 0.82459677]
Confusion Matrix KNN : 
 [[103   7  64]
 [ 36 268  23]
 [ 82  17 397]]
KNN Class Wise Accuracy :  [0.59195402 0.81957187 0.80040323]
Confusion Matrix RF : 
 [[ 87  26  61]
 [  9 305  13]
 [ 36  27 433]]
RF Class Wise Accuracy :  [0.5        0.93272171 0.87298387]
Confusion Matrix LR : 
 [[ 61  32  81]
 [  8 317   2]
 [ 15  29 452]]
LR Class Wise Accuracy :  [0.35057471 0.96941896 0.91129032]
Confusion Matrix DT : 
 [[ 85  25  64]
 [ 14 299  14]
 [ 47  29 420]]
D

In [181]:
idx = pd.Index(host_names_new) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = (idx.value_counts())
print(aq)

print(np.unique(host_names_new))

Here are all of the viral species in the dataset: 
 2991 entries in total
Human          1499
Neovison        931
Environment     561
dtype: int64
['Environment' 'Human' 'Neovison']


In [182]:
# print(svm_table_final)
# print(gauu_nb_table_final)
# print(mlp_table_final)
# print(knn_table_final)
# print(rf_table_final)
# print(lr_table_final)

#taking average of all k-fold performance values
final_mean_mat = []

# final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
NB   0.342695   0.410876  0.342695       0.218931    0.266308    0.342695   
MLP  0.722501   0.688006  0.722501       0.678899    0.590790    0.722501   
KNN  0.782347   0.785308  0.782347       0.780446    0.739816    0.782347   
RF   0.828151   0.820412  0.828151       0.817387    0.772896    0.828151   
LR   0.844199   0.839630  0.844199       0.828728    0.779319    0.844199   
DT   0.634703   0.604925  0.634703       0.615325    0.206374    0.634703   

      ROC AUC  
NB   0.539293  
MLP  0.733536  
KNN  0.808590  
RF   0.834190  
LR   0.841345  
DT   0.822243

# Adaboost

In [101]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
# >>> X, y = make_classification(n_samples=1000, n_features=4,
# ...                            n_informative=2, n_redundant=0,
# ...                            random_state=0, shuffle=False)

X = np.array(final_jernel_mat)
y =  np.array(final_labels_temp)

X_train , X_test , y_train, y_test = train_test_split(X, y, random_state=0)



In [102]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X_train, y_train)


AdaBoostClassifier(n_estimators=100, random_state=0)

In [103]:
# AdaBoostClassifier(n_estimators=100, random_state=0)
y_pred = clf.predict(X_test)
# clf.score(y_test, y_pred)

In [104]:
LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)

LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)

LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)

LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)

LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)

LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)

confuse = confusion_matrix(y_test, y_pred)
print("Confusion Matrix LR : \n", confuse)
print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
######################## Compute ROC curve and ROC area for each class ################
y_prob = y_pred
macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]

print(check)

Confusion Matrix LR : 
 [[  0   0   0   4   0]
 [  9   4   3 141   0]
 [  0   0   0   9   0]
 [ 23   7  24 430   0]
 [  0   0   0   3   0]]
LR Class Wise Accuracy :  [0.         0.02547771 0.         0.88842975 0.        ]
[0.6605783866057838, 0.6265440807458497, 0.6605783866057838, 0.6029258989237501, 0.17012138188608777, 0.6605783866057838, 0.4901721747358062]


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [105]:
uniqueWords = np.unique(final_protein_data_tmp)

In [106]:
uniqueWords_2 = list(uniqueWords)
uniqueWords

array(['', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N',
       'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y'], dtype='<U1')

In [107]:
final_freq_vec = []
for ind_freq in range(len(final_protein_data_tmp)):
    print(ind_freq,"/",len(final_protein_data_tmp))
    temp_freq_vec = [0]* len(uniqueWords)
    aaa = final_protein_data_tmp[ind_freq]
    for i in range(len(aaa)):
        ind = uniqueWords_2.index(aaa[i])
        temp_freq_vec[ind] = temp_freq_vec[ind] + 1
    final_freq_vec.append(temp_freq_vec)

0 / 2627
1 / 2627
2 / 2627
3 / 2627
4 / 2627
5 / 2627
6 / 2627
7 / 2627
8 / 2627
9 / 2627
10 / 2627
11 / 2627
12 / 2627
13 / 2627
14 / 2627
15 / 2627
16 / 2627
17 / 2627
18 / 2627
19 / 2627
20 / 2627
21 / 2627
22 / 2627
23 / 2627
24 / 2627
25 / 2627
26 / 2627
27 / 2627
28 / 2627
29 / 2627
30 / 2627
31 / 2627
32 / 2627
33 / 2627
34 / 2627
35 / 2627
36 / 2627
37 / 2627
38 / 2627
39 / 2627
40 / 2627
41 / 2627
42 / 2627
43 / 2627
44 / 2627
45 / 2627
46 / 2627
47 / 2627
48 / 2627
49 / 2627
50 / 2627
51 / 2627
52 / 2627
53 / 2627
54 / 2627
55 / 2627
56 / 2627
57 / 2627
58 / 2627
59 / 2627
60 / 2627
61 / 2627
62 / 2627
63 / 2627
64 / 2627
65 / 2627
66 / 2627
67 / 2627
68 / 2627
69 / 2627
70 / 2627
71 / 2627
72 / 2627
73 / 2627
74 / 2627
75 / 2627
76 / 2627
77 / 2627
78 / 2627
79 / 2627
80 / 2627
81 / 2627
82 / 2627
83 / 2627
84 / 2627
85 / 2627
86 / 2627
87 / 2627
88 / 2627
89 / 2627
90 / 2627
91 / 2627
92 / 2627
93 / 2627
94 / 2627
95 / 2627
96 / 2627
97 / 2627
98 / 2627
99 / 2627
100 / 2627

In [116]:
len(final_freq_vec[0])

22

In [131]:
X_train , X_test , y_train, y_test = train_test_split(X_transformed, host_names_new, random_state=0)

clf = svm.SVC(kernel="linear")

clf.fit(X_train,y_train)



SVC(kernel='linear')

In [134]:
y_pred = clf.predict(X_test)


LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)

LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)

LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)

LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)

LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)

LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)

confuse = confusion_matrix(y_test, y_pred)
print("Confusion Matrix LR : \n", confuse)
print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
######################## Compute ROC curve and ROC area for each class ################

y_prob = y_pred
macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]

print(check)

Confusion Matrix LR : 
 [[  1   0   0   3   0]
 [  3  21   8 124   1]
 [  2   2   0   5   0]
 [ 14  68   5 395   2]
 [  0   1   0   2   0]]
LR Class Wise Accuracy :  [0.25       0.13375796 0.         0.8161157  0.        ]
[0.634703196347032, 0.6049251481069075, 0.634703196347032, 0.6153247650223667, 0.20637396575442937, 0.634703196347032, 0.5229561828121182]


In [123]:
print(__doc__)

import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

# import some data to play with
iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features. We could
                      # avoid this ugly slicing by using a two-dim dataset
Y = iris.target


def my_kernel(X, Y):
    """
    We create a custom kernel:

                 (2  0)
    k(X, Y) = X  (    ) Y.T
                 (0  1)
    """
    M = np.array([[2, 0], [0, 1.0]])
    return np.dot(np.dot(X, M), Y.T)

aqq = my_kernel
aqq




Automatically created module for IPython interactive environment


<function __main__.my_kernel(X, Y)>

In [ ]:
h = .02  # step size in the mesh

# we create an instance of SVM and fit out data.
clf = svm.SVC(kernel=my_kernel)
clf.fit(X, Y)

In [ ]:
# Plot the decision boundary. For that, we will assign a color to each
# point in the mesh [x_min, x_max]x[y_min, y_max].
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.pcolormesh(xx, yy, Z, cmap=plt.cm.Paired)

# Plot also the training points
plt.scatter(X[:, 0], X[:, 1], c=Y, cmap=plt.cm.Paired, edgecolors='k')
plt.title('3-Class classification using Support Vector Machine with custom'
          ' kernel')
plt.axis('tight')
plt.show()