In [812]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt # graphs plotting
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline
import numpy
import csv 

from matplotlib import rc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean


from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

import statistics


# for Arial typefont
matplotlib.rcParams['font.family'] = 'Arial'


## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("Packages imported")

Packages imported


In [813]:
# Original DNA Sequences
path = "D:/University/Ph.D/Thesis/dataset/"
# file_name = path + "msa_0110"
# input_file_name = file_name + ".fasta"

file_name = "Spike_protein_20210615"
input_file_name = path + file_name + ".fasta"

# file_name = "msa_0223"
# input_file_name = "msa_0223.fasta"

# The fasta defline (name of a sequence) has the following format:
# Strain Name | Accession Number | Host Species | Virus Species) 
sequences_dictionary = {sequence.id : sequence.seq for sequence in SeqIO.parse(input_file_name,'fasta')}

print("Data Loaded")

Data Loaded


In [814]:
deflines = [entry for entry in sequences_dictionary.keys()]             # create a list of deflines
protein_sequences = [entry for entry in sequences_dictionary.values()]  # create a list of protein sequences 

In [815]:
len(deflines)

1898321

# Taking less data for Analysis

In [816]:
# # temp_range = 1835000 #we can adjust number of datapoints here
# temp_range = 100000 #we can adjust number of datapoints here


# deflines = deflines[0:temp_range]
# protein_sequences = protein_sequences[0:temp_range]

In [817]:
aa = (protein_sequences)
result_path = "D:/University/RA/covid_origin/Results/"

In [818]:
deflines

['Spike|hCoV-19/Wuhan/WIV04/2019|2019-12-30|EPI_ISL_402124|Original|hCoV-19^^Hubei|Human|Wuhan',
 'Spike|hCoV-19/Wales/PHWC-246D7/2020|2020-03-18|EPI_ISL_419442|Original|hCoV-19^^Wales|Human|Wales',
 'Spike|hCoV-19/France/PAC-IHU-3345-1/2021|2021-02-16|EPI_ISL_1109968|Original|hCoV-19^^Marseille|Human|MEPHI|MEPHI|Levasseur|France',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR031/2020|2020-06-05|EPI_ISL_1210558|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR039/2020|2020-06-04|EPI_ISL_1210566|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR058/2020|2020-05-27|EPI_ISL_1210579|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR026/2020|2020-05-18|EPI_ISL_1210553|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR047/2020|2020-05-29|EPI_ISL_1210572|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Russia/RSMU_GC_SAR011/2020|2020-05-22|EPI_ISL_1210539|Original|hCoV-19^^Moscow|Human|FSBI',
 'Spike|hCoV-19/Ru

# Check for Missing values and remove them

In [819]:
missing_val_check = []
for i in range(0, len(deflines)):
    length_check = len(deflines[i])
    if length_check<50:
        print(i,', Length = ', len(deflines[i]))
        missing_val_check.append(i)

82 , Length =  19
186 , Length =  19
2715 , Length =  17
2787 , Length =  22
2816 , Length =  20
2992 , Length =  18
3023 , Length =  18
3254 , Length =  19
7348 , Length =  19
8780 , Length =  28
9109 , Length =  20
9200 , Length =  19
9513 , Length =  19
10518 , Length =  17
11165 , Length =  18
13904 , Length =  21
16739 , Length =  22
17427 , Length =  20
18888 , Length =  20
25813 , Length =  24
31700 , Length =  23
33807 , Length =  19
38767 , Length =  19
61874 , Length =  20
66827 , Length =  32
96929 , Length =  25
98799 , Length =  21
99966 , Length =  34
102455 , Length =  28
102956 , Length =  29
162433 , Length =  28
163415 , Length =  33
181453 , Length =  47
201550 , Length =  29
212638 , Length =  22
242952 , Length =  30
246016 , Length =  24
256217 , Length =  20
259666 , Length =  27
263780 , Length =  33
265592 , Length =  29
266294 , Length =  31
301129 , Length =  29
306200 , Length =  21
312055 , Length =  27
320878 , Length =  30
352481 , Length =  23
361744 , L

In [820]:
#removing missing values rows
for i in range(0, len(missing_val_check)):
    deflines.remove(deflines[missing_val_check[i]-i])
    protein_sequences.remove(protein_sequences[missing_val_check[i]-i])
#     targets.remove(targets[missing_val_check[i]-i])

In [821]:
final_pca_num = 60

In [822]:
np.unique(protein_sequences[0])

array(['*', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N',
       'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y'], dtype='<U1')

In [823]:
idx = pd.Index(protein_sequences[4]) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 1274 entries in total
L    108
S     99
V     97
T     96
N     88
G     83
A     79
F     77
I     77
Q     62
K     61
D     61
P     58
Y     54
E     48
R     42
C     40
H     17
M     14
W     12
*      1
dtype: int64


In [824]:
cities = []
protein_sequences_old = []
deflines_old = []
for i in range(0, len(deflines)):
    if(len(deflines[i].split("|"))==8):
#         aaa = (deflines[i].split("|")[7])
        aaa = (deflines[i].split("|")[1])
        aaaa = aaa.split("/")[1]
#         aaaa
        
        cities.append(aaaa)
        protein_s1 = protein_sequences[i]
        protein_sequences_old.append(protein_s1[14:686])  # S1 spike protein
        deflines_old.append(deflines[i])

# protein_sequences = protein_sequences_old
print(cities)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [825]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq[0:60])

# SouthAfrica, Brazil, England

Here are all of the viral species in the dataset: 
 1583279 entries in total
USA            416726
England        362872
Denmark        105138
Germany         91808
Japan           50532
Sweden          47391
Scotland        46446
Canada          42818
Switzerland     41470
Netherlands     37441
Wales           34390
Italy           29576
France          28922
Spain           22742
Belgium         19823
Austria         18649
India           16239
Ireland         15194
Australia       14984
Poland          14009
Slovenia        13024
Norway          10147
Israel           9623
Luxembourg       9133
Portugal         6808
Greece           6062
Finland          5530
Iceland          5085
Turkey           5016
Mexico           4643
Lithuania        3443
Brazil           3400
Russia           2653
Slovakia         2639
Singapore        2559
Bulgaria         2546
Qatar            2488
Latvia           2465
Bangladesh       1691
Philippines      1239
Thailand         1236
Peru             1200

In [826]:
# protein_sequences = protein_sequences_old
# deflines = deflines_old
# cities = []
# for i in range(0, len(deflines)):
#     aaa = (deflines[i].split("|"))
#     aaa_1 = aaa[5]
#     aaa_2 = aaa_1.replace('hCoV-19^^','')
#     cities.append(aaa_2)
# print(cities)

In [827]:
# # USA_STATES = ['Alaska','Arizona', 'Atlanta', 'Alameda', 'Atlas', 'CA','California', 'Connecticut','Delaware',
# #               'Emory','FL','Florida','GA','Houston','IL','Illinois','Indiana','Kansas','Kentucky',
# #               'LA','Maryland', 'Massachusetts', 'Michigan','Minnesota','Missouri','NV', 'NV-Southern',
# #               'NYU','Nevada','OH', 'OHSU', 'Ohio',"Ontario's",'Oregon','Seattle','Stanford','TN', 'TX',
# #               'Texas', 'UC', 'UCD','UCLA', 'UCSC', 'UCSF', 'UHCW','US', 'USC', 'USCA','United','Utah',
# #               'Virginia', 'Washington', 'Wisconsin','Yale','Riverside', 'Wyoming', 'Colorado']

# USA_STATES = ['Houston']
# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(USA_STATES)):
#         if (cities[ind_tmp]==USA_STATES[asdd]):
#             cities[ind_tmp] = 'USA'
#             counter = counter+1
# print(counter)


In [828]:
# USA_EAST_STATES = ['Alameda', 'Atlas', 'Delaware',
#               'Emory','FL','Florida','Houston','IL','Illinois','Indiana','Kentucky',
#               'LA','Maryland', 'Massachusetts', 'Michigan','Minnesota','Missouri','NV', 'NV-Southern',
#               'Nevada','OH', 'OHSU', 'Ohio',"Ontario's",'Oregon','Stanford','TN',
#                'UCD', 'UCSC', 'UCSF', 'UHCW','US', 'USC', 'USCA','United',
#                'Wisconsin','Yale','Riverside',  'Colorado']



# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(USA_STATES)):
#         if (cities[ind_tmp]==USA_STATES[asdd]):
#             cities[ind_tmp] = 'USA'
#             counter = counter+1
# print(counter)


In [829]:
# USA_WEST_STATES = [, 'Alameda', 'Atlas','Delaware',
#               'Emory','FL','Florida','GA','Houston','IL','Illinois','Indiana','Kansas','Kentucky',
#               'LA','Maryland', 'Massachusetts', 'Michigan','Minnesota','Missouri','NV', 'NV-Southern',
#               'Nevada','OH', 'OHSU', 'Ohio',"Ontario's",'Oregon','Stanford','TN', 'TX',
#               'Texas', 'UC', 'UCD', 'UCSC', 'UCSF', 'UHCW','US', 'USC', 'USCA','United','Utah',
#                'Wisconsin','Yale','Riverside','Colorado']
# 'Alaska', 'California', 'CA', 'UC', 'UCLA', 'Seattle', 'Wyoming', 'Arizona'

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(USA_STATES)):
#         if (cities[ind_tmp]==USA_STATES[asdd]):
#             cities[ind_tmp] = 'USA'
#             counter = counter+1
# print(counter)


In [830]:
# USA_MIDDLE_STATES = ['Arizona', 'Alameda', 'Atlas', 'CA','Delaware',
#               'Emory','FL','Florida','GA','Houston','IL','Illinois','Indiana','Kentucky',
#               'LA','Maryland', 'Massachusetts', 'Michigan','Minnesota','Missouri','NV', 'NV-Southern',
#               'Nevada','OH', 'OHSU', 'Ohio',"Ontario's",'Oregon','Stanford','TN', 'TX',
#               'UC', 'UCD', 'UCSC', 'UCSF', 'UHCW','US', 'USC', 'USCA','United',
#                'Wisconsin','Yale','Riverside',  'Colorado']
# Texas, 'TX', Wyoming, Utah, Kansas

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(USA_STATES)):
#         if (cities[ind_tmp]==USA_STATES[asdd]):
#             cities[ind_tmp] = 'USA'
#             counter = counter+1
# print(counter)


In [831]:
# Canada_states = ['Alberta',"Ontario's",'Toronto']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(Canada_states)):
#         if (cities[ind_tmp]==Canada_states[asdd]):
#             cities[ind_tmp] = 'Canada'
#             counter = counter+1
            
# print(counter)

In [832]:
# China_states = ['Wuhan','Guangdong','Guam','Shanghai']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(China_states)):
#         if (cities[ind_tmp]==China_states[asdd]):
#             cities[ind_tmp] = 'China'
#             counter = counter+1
            
# print(counter)

In [833]:
# Indian_States = ['Gandhi', 'Gujarat','Sanjay', 'Tata','Indian','Rajendra']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(Indian_States)):
#         if (cities[ind_tmp]==Indian_States[asdd]):
#             cities[ind_tmp] = 'India'
#             counter = counter+1
            
# print(counter)

In [834]:
# # Wales           21741
# # Liverpool        6991
# # Lincolnshire     1015
# # Leeds             473

# # UK_States = ['Leeds','Lincolnshire','Liverpool','Wales']
# UK_States = ['Wales']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(UK_States)):
#         if (cities[ind_tmp]==UK_States[asdd]):
#             cities[ind_tmp] = 'UK'
#             counter = counter+1
            
# print(counter)

In [835]:
# # Swedish        41666
# # Norwegian        976
# # Oslo             307
# # Uppsala           52
# # WESTCHESTER       33
# # Levanger           3

# # Scandinavia = ['WESTCHESTER','Levanger','Oslo', 'Uppsala','Norwegian','Swedish']
# Scandinavia = ['Swedish']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(Scandinavia)):
#         if (cities[ind_tmp]==Scandinavia[asdd]):
#             cities[ind_tmp] = 'Sweden'
#             counter = counter+1
            
# print(counter)

In [836]:
# japan_states = ['Nebraska','Osaka','Sakai','Tokyo']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(japan_states)):
#         if (cities[ind_tmp]==japan_states[asdd]):
#             cities[ind_tmp] = 'Japan'
#             counter = counter+1
            
# print(counter)

In [837]:
# continent_america = ['USA','Canada']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(continent_america)):
#         if (cities[ind_tmp]==continent_america[asdd]):
#             cities[ind_tmp] = 'America'
#             counter = counter+1
            
# print(counter)

In [838]:
# continent_europe = ['Lithuanian','Louisiana','Austrian','Scandinavia','UK']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(continent_europe)):
#         if (cities[ind_tmp]==continent_europe[asdd]):
#             cities[ind_tmp] = 'Europe'
#             counter = counter+1
            
# print(counter)

In [839]:
# continent_asia = ['Korian','India','Israel','Palestinian', 'Philippine','Japan','China']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(continent_asia)):
#         if (cities[ind_tmp]==continent_asia[asdd]):
#             cities[ind_tmp] = 'ASIA'
#             counter = counter+1
            
# print(counter)

In [840]:
# continent_africa = ['Egyptian','Nigeria','Uganda']

# counter = 1
# for ind_tmp in range(len(cities)):
#     for asdd in range(len(continent_africa)):
#         if (cities[ind_tmp]==continent_africa[asdd]):
#             cities[ind_tmp] = 'Africa'
#             counter = counter+1
            
# print(counter)

In [841]:
# strings_to_retain = ['Korian','Egyptian','India','Israel','Lithuanian','Louisiana',
#                     'Nigeria','Palestinian', 'Philippine','Austrian','Uganda','Japan',
#                      'Scandinavia','UK','China','Canada','USA']
# strings_to_retain = ['USA','Scandinavia','UK','Canada','Israel','Dutch','Austrian']
# strings_to_retain = ['America','Europe','Africa','ASIA']
# strings_to_retain = ['Florida','Houston', 'Utah', 'Colorado', 'Michigan', 'Wisconsin', 'Illinois','Wyoming']

# Lithuania      3443
# Brazil         3400
# Russia         2653
# Slovakia       2639
# Singapore      2559
# Bulgaria       2546
# Qatar          2488
# Latvia         2465
# Bangladesh     1691
# Philippines    1239
# Thailand       1236
# Peru           1200
# Aruba          1075

# Israel           9623
# Luxembourg       9133
# Portugal         6808
# Greece           6062
# Finland          5530

# Iceland          5085
# Turkey           5016
# Mexico           4643

# Final => 'Brazil', 'Malaysia', 'Argentina', 'Iceland'

strings_to_retain = ['Brazil','USA', 'England', 'Iceland', 'Denmark']
#                      'Bulgaria', 'Qatar', 'Latvia', 'Bangladesh', 'Philippines', 'Thailand', 'Peru', 'Aruba']

In [842]:
cities_reduced = []
for ind_cities in range(len(strings_to_retain)):
    indices = [i for i, x in enumerate(cities) if x == strings_to_retain[ind_cities]]
    cities_reduced.extend(indices)

# cities_reduced.sort()

In [843]:
from operator import itemgetter 

cities_reduced_2 = itemgetter(*cities_reduced)(cities)
protein_sequences = itemgetter(*cities_reduced)(protein_sequences_old)
deflines = itemgetter(*cities_reduced)(deflines_old)

cities = cities_reduced_2
# cities_new_2 = cities_reduced_2

In [844]:
len(deflines)

893221

In [845]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Dataset distribution: \n', len(idx),"entries in total")
print(idx.value_counts())

Dataset distribution: 
 893221 entries in total
USA        416726
England    362872
Denmark    105138
Iceland      5085
Brazil       3400
dtype: int64


# selecting equal distribution of true labels for classification

In [846]:
# 'Brazil','USA', 'England', 'Iceland', 'Denmark'

initial_ind = 2000

USA_count = 1000
USA_indices_2 = [i for i, x in enumerate(cities) if x == "USA"]
USA_indices = USA_indices_2[initial_ind:(USA_count+initial_ind)]

Scandinavia_count = 1000
Scandinavia_indices_2 = [i for i, x in enumerate(cities) if x == "England"]
Scandinavia_indices = Scandinavia_indices_2[initial_ind:(Scandinavia_count+initial_ind)]

Dutch_count = 1000
Dutch_indices_2 = [i for i, x in enumerate(cities) if x == "Brazil"]
Dutch_indices = Dutch_indices_2[initial_ind:(Dutch_count+initial_ind)]

UK_count = 1000
UK_indices_2 = [i for i, x in enumerate(cities) if x == "Iceland"]
UK_indices = UK_indices_2[initial_ind:(UK_count+initial_ind)]

Canada_count = 1000
Canada_indices_2 = [i for i, x in enumerate(cities) if x == "Denmark"]
Canada_indices = Canada_indices_2[initial_ind:(Canada_count+initial_ind)]

# # Israel_count = 2335
# # Israel_indices_2 = [i for i, x in enumerate(cities) if x == "Israel"]
# # Israel_indices = Israel_indices_2[0:Israel_count]

# # Austrian_count = 2240 
# # Austrian_indices_2 = [i for i, x in enumerate(cities) if x == "Austrian"]
# # Austrian_indices = Austrian_indices_2[0:Austrian_count]




In [847]:
city_index_list = []
city_index_list.extend(USA_indices)
city_index_list.extend(Scandinavia_indices)
city_index_list.extend(Dutch_indices)
city_index_list.extend(UK_indices)
city_index_list.extend(Canada_indices)
# # city_index_list.extend(Israel_indices)
# # city_index_list.extend(Austrian_indices)

In [848]:
cities_final = []
protein_sequences_final = []
deflines_final = []
for i in range(0, len(city_index_list)):
    cities_final.append(cities[city_index_list[i]])
    protein_sequences_final.append(protein_sequences[city_index_list[i]])
    deflines_final.append(deflines[city_index_list[i]])

In [849]:
cities = cities_final
protein_sequences = protein_sequences_final
deflines = deflines_final

In [850]:
# len(cities)

# Final Data Analytics

In [851]:

human_virus_species_set =  np.unique(cities)


In [852]:
human_virus_species_set

array(['Brazil', 'Denmark', 'England', 'Iceland', 'USA'], dtype='<U7')

In [853]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
print(idx.value_counts())

Here are all of the viral species in the dataset: 
 5000 entries in total
USA        1000
Denmark    1000
England    1000
Brazil     1000
Iceland    1000
dtype: int64


In [854]:
dates_Unordered = cities

In [855]:
idx = pd.Index(protein_sequences[0]) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 672 entries in total
T    57
N    54
V    53
S    51
L    50
F    47
G    46
P    36
A    35
Y    35
I    32
D    30
K    30
R    29
Q    26
E    23
C    20
H     9
W     7
M     2
dtype: int64


In [856]:
def encoding(sequence, type_of_encoding):
    # define universe of possible input values
#             alphabet = 'ABCDEFGHIJKLMNPQRSTUVWXYZ-'
#     alphabet = 'ACGTNYSWKRMH-'
#     alphabet = 'LSVTNGAFIQDKPYERCHMWX*'
#     alphabet = 'ABCDGTNYSWKRMHV-'
#     alphabet = 'ACDEFGHIKLMNPQRSTVWXY*'
    alphabet = 'ACDEFGHIKLMNPQRSTVWXY*'
    # define a mapping of chars to integers
    char_to_int = dict((c, i) for i, c in enumerate(alphabet))


    # integer encoding
    integer_encoded = [char_to_int[char] for char in sequence]

    # one-hot encoding
    onehot_encoded = list()
    for value in integer_encoded:
        letter = [0 for _ in range(len(alphabet)-1)]
        if value != len(alphabet)-1:
            letter[value] = 1
        onehot_encoded.append(letter)
    flat_list = [item for sublist in onehot_encoded for item in sublist]

    if type_of_encoding == "onehot":
        return flat_list
    else:
        return integer_encoded

In [857]:
# Check the length of each sequence as they can be different
seq_length = []
for i in range(0, len(deflines)):
    seq_length.append(len(protein_sequences[i]))

In [858]:
np.unique(protein_sequences[i])

array(['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P',
       'Q', 'R', 'S', 'T', 'V', 'W', 'Y'], dtype='<U1')

In [859]:
idx = pd.Index(seq_length) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aabc = idx.value_counts()
print((aabc))
aabc = aabc.tolist()
# print(np.transpose(aabc))


Here are all of the viral species in the dataset: 
 5000 entries in total
672    4958
61       21
604       5
139       2
347       1
114       1
260       1
368       1
417       1
198       1
279       1
234       1
270       1
314       1
426       1
11        1
159       1
4         1
dtype: int64


In [860]:
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
#     print(aabc)

In [861]:
# we create a list of sequences as objects of the class fasta_sequence
# all sequences are encoded with one-hot encoding (it is the default option of the constructor of the class)
sequences = []
deflines_new = []
cities_new = []
#     if(len(protein_sequences[i])==3813):
#     if(len(protein_sequences[i])==31753):
#     if(len(protein_sequences[i])==31753):
counter = 1
for i in range(0, len(deflines)):
#     if(len(protein_sequences[i])==1274):
    if(len(protein_sequences[i])==672):
        print("Apply encoding", counter, "/", aabc[0])
        counter = counter+1
        current_sequence = encoding(protein_sequences[i],"onehot")
        sequences.append(current_sequence)
        deflines_new.append(deflines[i])
        cities_new.append(cities[i])
    
# print("Apply encoding")

Apply encoding 1 / 4958
Apply encoding 2 / 4958
Apply encoding 3 / 4958
Apply encoding 4 / 4958
Apply encoding 5 / 4958
Apply encoding 6 / 4958
Apply encoding 7 / 4958
Apply encoding 8 / 4958
Apply encoding 9 / 4958
Apply encoding 10 / 4958
Apply encoding 11 / 4958
Apply encoding 12 / 4958
Apply encoding 13 / 4958
Apply encoding 14 / 4958
Apply encoding 15 / 4958
Apply encoding 16 / 4958
Apply encoding 17 / 4958
Apply encoding 18 / 4958
Apply encoding 19 / 4958
Apply encoding 20 / 4958
Apply encoding 21 / 4958
Apply encoding 22 / 4958
Apply encoding 23 / 4958
Apply encoding 24 / 4958
Apply encoding 25 / 4958
Apply encoding 26 / 4958
Apply encoding 27 / 4958
Apply encoding 28 / 4958
Apply encoding 29 / 4958
Apply encoding 30 / 4958
Apply encoding 31 / 4958
Apply encoding 32 / 4958
Apply encoding 33 / 4958
Apply encoding 34 / 4958
Apply encoding 35 / 4958
Apply encoding 36 / 4958
Apply encoding 37 / 4958
Apply encoding 38 / 4958
Apply encoding 39 / 4958
Apply encoding 40 / 4958
Apply enc

In [862]:
encoded_sequences = sequences
deflines = deflines_new
cities = cities_new

In [863]:
np.unique(cities)

array(['Brazil', 'Denmark', 'England', 'Iceland', 'USA'], dtype='<U7')

In [864]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
print(idx.value_counts())

Here are all of the viral species in the dataset: 
 4958 entries in total
USA        995
Brazil     993
Denmark    992
England    992
Iceland    986
dtype: int64


# t-SNE Logic

In [865]:
# from sklearn.manifold import TSNE

# # We embed all our sequences into 2D vectors with help of TSNE
# X_embedded = TSNE(n_components = 2, perplexity = 30, random_state = 1).fit_transform(encoded_sequences)

In [866]:
# # order_top_hosts =  ['Avian CoV', 'PEDV', 'BCoV-1', 'MERS', 'HKU15', 'SARS-2', 'Other CoVs']
# order_top_hosts =  ['Colorado', 'Florida', 'Houston', 'Illinois', 'Michigan', 'Utah','Wisconsin', 'Wyoming']
# ordered_markers_top_hosts = {'Colorado': 'D', 'Florida': '*', 
#                                'Houston': 'P',   'Illinois': 'X', 'Michigan': '.', 
#                              'Utah': '+', 'Wisconsin': 'v', 'Wyoming': 'a'}
# # colors_top_hosts = {'Europe' : 'lightcoral', 'NorthAmerica' : 'grey',
# #                       'Oceania' : 'orange', 'Asia': 'rosybrown',  
# #                       'Other-Regions' : 'black'}

# data_frame_top_hosts = pd.DataFrame({'1st coordinate of the embedded vector': 
#                                    X_embedded[:,0], 
#                            '2nd coordinate of the embedded vector': X_embedded[:,1], 
#                            'Virus Origin:': cities})

# picture_2 = sns.scatterplot(x = '1st coordinate of the embedded vector, Total Data Points: ', 
#             y = '2nd coordinate of the embedded vector', 
#             hue = 'Virus Origin:', 
#             hue_order = order_top_hosts,
#             markers = ordered_markers_top_hosts,
# #             palette = colors_top_hosts,
#             data = data_frame_top_hosts,           
#             legend = 'full',
# #             ax = ax12,
#             linewidth=0.5,
#             style = 'Virus Origin:')

# # plt.ylim(-35, 30)

# # picture.append(picture_2)
# # plt.savefig('D:/University/Ph.D/Thesis/points_clustering_' + dataset_name + '_data_points_' + size_name + '.png')

# Sort the data with respect to dates

In [867]:
# dates_ordered = sorted(dates_Unordered)

In [868]:
# X = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
# Y = [ 0,   1,   1,    0,   1,   2,   2,   0,   1]
X = encoded_sequences
Y = dates_Unordered
Z = [x for _,x in sorted(zip(Y,X))]
# print(Z)  # ["a", "d", "h", "b", "c", "e", "i", "f", "g"]

In [869]:
data = pd.DataFrame(encoded_sequences) #unsorted data information
# data = pd.DataFrame(Z) #sorted data information

In [870]:
data.shape

(4958, 14112)

In [871]:
X = cities
Y = dates_Unordered
Z_cities = [x for _,x in sorted(zip(Y,X))] #sorted cities

In [872]:
data_labels = cities #unsorted data information
# data_labels = Z_cities #sorted data information

# Getting familiar with the data

In [873]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
print(idx.value_counts())

Here are all of the viral species in the dataset: 
 4958 entries in total
USA        995
Brazil     993
Denmark    992
England    992
Iceland    986
dtype: int64


In [874]:
len(data_labels)

4958

# Classification and Dimensionality redction

In [875]:
# X_train, X_test, y_train, y_test = train_test_split(
#     data,data_labels,
#     test_size=0.3,
#     random_state=0)
X_train, X_test, y_train, y_test = train_test_split(
    data,data_labels,
    test_size=0.3,
    shuffle=True)
X_train.shape, X_test.shape

((3470, 14112), (1488, 14112))

# Classification Function

In [876]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

  #creating a set of all the unique classes using the actual class list
  unique_class = set(actual_class)
  roc_auc_dict = {}
  for per_class in unique_class:
    #creating a list of all the classes except the current class 
    other_class = [x for x in unique_class if x != per_class]

    #marking the current class as 1 and all other classes as 0
    new_actual_class = [0 if x in other_class else 1 for x in actual_class]
    new_pred_class = [0 if x in other_class else 1 for x in pred_class]

    #using the sklearn metrics method to calculate the roc_auc_score
    roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
    roc_auc_dict[per_class] = roc_auc
    
    
  check = pd.DataFrame(roc_auc_dict.items())
  return mean(check)

# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,NB_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,MLP_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,knn_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,fr_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


# LSH Functions

In [877]:
# Locality Sensitive Hashing
# https://github.com/rashmishrm/Movie-Reviews-Classification/blob/master/lsh.py

#!/usr/bin/python
r""" Example of Approximate Nearest Neighbors using Locality Sensitive Hashing (LSH)
	with Hamming Distance, Jaccard Coefficient and Cosine Similarity.
	Given a training/database set of objects and a test/query set of objects,
	find the k-Nearest Neighbors (k-NN) for each of the objects in the query set
	and report the accuracy of the result (measured as average recall, i.e., the mean
	of the ratios, number of true neighbors found / number of neighbors sought).
	
	Note: This is an academic implementation meant to understand the general LSH
	search mechanism. Much better implementations and extensions of the basic LSH 
	algorithm exist in practice.
"""
import time
import argparse
import numpy as np
from random import randint
from numpy.linalg import norm
from operator import itemgetter
from collections import defaultdict
from sklearn.datasets import make_blobs


__all__ = ['blsh', 'clsh', 'hlsh', 'jlsh']

class blsh(object):
    r""" Example data structure for computing Approximate Nearest Neighbors 
    using Locality Sensitive Hashing (LSH) with Hamming Distance, 
    Jaccard Coefficient and Cosine Similarity.
    
    This is a base abstract class that is extended by three concrete classes:
    - clsh implements an LSH table for Cosine similarity. 
    - hlsh implements an LSH table for Hamming distance. 
    - jlsh implements an LSH table for Jaccard coefficient. 
    
    Example usage:
        L = clsh(X, ntables=10, nfunctions=10)
        N = L.findNeighbors(Y, k=5)
            
    Attributes
    ----------
    ntables : int
        Number of hash tables to create
    nfunctions : int
        Number of functions to use for each table
        
    Notes:
    ------
    
    This is an academic implementation meant to understand the general LSH
    search mechanism. Much better implementations and extensions of the basic LSH 
    algorithm exist in practice.
    """
    
    def __init__(self, X, ntables=10, nfunctions=10):
        r""" Initialize an elsh structure.
        
        Parameters:
            X: numpy 2D array (matrix). Each object takes up a row of X.
            ntables: int, Number of hash tables to create.
            nfunctions: int, Number of functions to use for each table.
        """
        self.X = np.copy(X)
        self.ntables = ntables
        self.nfunctions = nfunctions
        self.nsims = 0 # counter for number of computed similarities
        self.sim = True # whether this is a similarity function, not a distance function
        # hash functions, one set of nfunctions functions for each table
        self.hfts = [{} for _ in range(ntables)]    
        # the hash tables
        self.tables = [defaultdict(set) for _ in range(ntables)]
        # hash data in X
        self._hashData(self.X)

    def hash(self, x, tid=0, fid=0):
        r""" Hash vector x using the function fid in table tid.
        Implemented by subclasses.
        """
        raise NotImplementedError()

    def signature(self, x, tid=0):
        r""" Get the signature (bucket ID) of x in table tid.
        
        Return: string
        """
        hk = ''
        for fid in range(self.nfunctions):
            h = self.hash(x, tid, fid)
            # We use a simple table hash key, concatenating the string 
            # representations of the hash function values returned in h.
            # This is equivalent to the AND operation, i.e., two objects
            # must have the same h value for all nfunctions functions to
            # be added to the same bucket (think set intersection!).
            hk += '%d' % h
        return hk
        
    @staticmethod
    def prox(x, y):
        r""" Compute the proximity (similarity or distance) of two vectors
        """
        raise NotImplementedError()
    
    def _hashData(self, X):
        r""" Hash a set of data points.
        We take an AND + OR approach to constructing hashes. We concatenate 
        hash functions in each table to decrease the probability of the collision
        of distant points as much as possible. This, in turn, increases precision.
        By considering points found in multiple tables, we increase the probability
        of the collision of close points, which increases recall. 
        """
    
        for i in range(X.shape[0]):
            x = X[i,:] # row i in X
            for tid in range(self.ntables):
                table = self.tables[tid]
                hk = self.signature(x, tid)
                table[hk].add(i) # add row i to bucket hk in table tid

    def search(self, y, k=5):
        r""" Find neighbors for object y given an already constructed set of LSH tables,
        returning the k nearest neighbors found.
        We hash y in each table, and compare against the union of all found object ids.
        
        Return: a list of tuples of neighbor id and similarity value
        """
        cands = set()
        for tid in range(self.ntables):
            table = self.tables[tid]
            hk = self.signature(y, tid)
            cands = cands.union(table[hk])
        sims = [(i, self.prox(self.X[i,:], y)) for i in cands]
        self.nsims += len(sims)
        sims.sort(key=itemgetter(1), reverse=self.sim) # sort by value
        if len(sims) < k:
            k = len(sims)
            
        return sims[:k]
    
    def findNeighbors(self, Y, k=5, retvals=False):
        r""" Find k-NN using for a set of objects using the LSH structure
        
        Return: An array containing up to k neighbors for each row in Y. If less than
        k neighbors are found, the remaining IDs will be -1. If retval is True, a second
        array will be returned with corresponding values for the nearest neighbors.
        """
        nte = Y.shape[0]
        nbrs = np.full((nte, k), -1, dtype=np.int) # in case some searches return less than k items
        if retvals is True:
            nvals = np.zeros((nte, k), dtype=np.double)
	# reset nsims
        self.nsims = 0
        
        for i in range(nte):
            sims = self.search(Y[i,:], k=k)
            nk = len(sims)
            if not nk:
                continue
            nbr, sim = zip(*sims) # split neighbor ids and values
            nbrs[i, :nk] = nbr
            if retvals:
                nvals[i, :nk] = sim
        
        if retvals:
            return nbrs, nvals
        return nbrs
    

class clsh(blsh):
    r""" LSH table for Cosine similarity
    """
    
    def hash(self, x, tid=0, fid=0):
        r""" Hash vector x using the function fid in table tid.
        
        Return: binary value (1|0)
        """
        assert tid < self.ntables
        assert fid < self.nfunctions
        
        hft = self.hfts[tid] # a map containing hash functions
        m = len(x) # number of features
        
        if fid not in hft:
            # generate random unit vector
            r = np.random.randn(m)
            r = r/norm(r)
            hft[fid] = r
        
        r = hft[fid]     # random unit vector
        hr = x.dot(r.T)  # dot product of x with r
        return 1 if hr > 0 else 0
        
    @staticmethod
    def prox(x, y):
        r""" Compute the Cosine similarity of two vectors
        
        Return: double
        """
        return x.dot(y.T)/(norm(x)*norm(y))
    

class jlsh(blsh):
    r""" LSH table for Jaccard coefficient
    """
    
    def hash(self, x, tid=0, fid=0):
        r""" Hash vector x using the function fid in table tid.
        
        Return: int
        """
        assert tid < self.ntables
        assert fid < self.nfunctions
        
        hft = self.hfts[tid] # a map containing hash functions
        m = len(x) # number of features
        
        if fid not in hft:
            # generate random permutation of feature ids
            hft[fid] = np.random.permutation(m)
            
        p = hft[fid]
        for i in range(m):
            if x[ p[i] ]:
                return p[i] # first feature with non-zero value in x according to permutation p
        return m
        
    @staticmethod
    def prox(x, y):
        r""" Compute the Jaccard coefficient of two vectors
        
        Return: double
        """
        z = x+y
        return np.sum(z == 2) / (0.0 + np.sum(z > 0))



class hlsh(blsh):
    r""" LSH table for Hamming distance
    """
    
    def __init__(self, X, ntables=10, nfunctions=10):
        r""" Initialize an hlsh structure.
        
        Parameters:
            X: numpy 2D array (matrix). Each object takes up a row of X.
            ntables: int, Number of hash tables to create.
            nfunctions: int, Number of functions to use for each table.
        """
        super(hlsh, self).__init__(X, ntables=ntables, nfunctions=nfunctions)
        self.sim = False
    
    def hash(self, x, tid=0, fid=0):
        r""" Hash vector x using the function fid in table tid.
        
        Return int
        """
        assert tid < self.ntables
        assert fid < self.nfunctions
        
        hft = self.hfts[tid] # a map containing hash functions
        m = len(x) # number of features
        
        if fid not in hft:
            # generate random feature id
            hft[fid] = randint(0, m-1)
            
        return x[ hft[fid] ] # value in x for the chosen random feature 
        
    @staticmethod
    def prox(x, y):
        r""" Compute the Hamming distance of two vectors
        
        Return: int
        """
        return np.sum(x!=y)


def get_args():
    r""" Parse arguments for the program    
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("-sim", "--sim", type=str, default="jac", help="Which similarity to compute for, e.g. cos|jac")
    parser.add_argument("-n", "--nsamples", type=int, default=1000, help="Number of random samples to generate")
    parser.add_argument("-m", "--nfeatures", type=int, default=100, help="Number of features for each sample")
    parser.add_argument("-f", "--nfunctions", type=int, default=2, help="Number of random hash functions to use")
    parser.add_argument("-t", "--ntables", type=int, default=10, help="Number of tables/signatures to create")
    parser.add_argument("-k", "--nnbrs", type=int, default=5, help="Number of nearest neighbors to find")
    
    return parser.parse_args()


def generateSamples(nsamples=10000, nfeatures=1000, nclusters=100, clusterstd=50, binary=False):
    r""" Generate random samples for the experiment
    """
    # generate samples from several clusters (blobs)
    X, _ = make_blobs(n_samples=nsamples, n_features=nfeatures, 
    	centers=nclusters, cluster_std=clusterstd)
    
    # binarize the data if necessary by taking only values above the mean
    if binary:
        mu = np.mean(X) + np.random.randn()
        X[X > mu] = 1
        X[X <= mu] = 0
        X = np.array(X, dtype=np.int)
        
    # split data into train and test sets, using a 90:10 split
    c = int(X.shape[0]/10)
    if c > 1000:
        c = 1000 # max 1000 test items
    X_te = X[:c]
    X_tr = X[c:]
    
    return X_tr, X_te


def findNeighborsBrute(X_tr, X_te, k=5, sim="cos", retvals=False):
    r""" Find k-NN using a brute-force approach
    """
    nte = int(X_te.shape[0]) # number of test samples
    ntr = int(X_tr.shape[0]) # number of training samples
    # space to store neighbors 
    nbrs = np.zeros((nte, k), dtype=np.int)
    if retvals is True:
        nvals = np.zeros((nte, k), dtype=np.double)
    
    # choose the right proximity function
    if sim == "cos":
        prox = clsh.prox
    elif sim == "ham":
        prox = hlsh.prox
    elif sim == "jac":
        prox = jlsh.prox
    else:
        raise ValueError("Incorrect proximity function. Try one of: cos, ham, or jac.")
    
    # find the nearest neighbors for each item in the test set
    for i in range(nte):
        # compute proximity of X_te[i] to all X_tr objects and sort list,
        # returning the IDs of the closest objects
        sims = [prox(X_te[i],X_tr[j]) for j in range(ntr)]
        p = np.argsort(sims)
        if sim != "ham":
            p = p[::-1] # reverse list direction
        nbrs[i,:] = p[:k]
        if retvals is True:
            nvals[i,:] = [sims[k] for k in p[:k]]
    
    if retvals is True:
        return nbrs, nvals
    return nbrs
 
def recall(nbrsTest, nbrsExact):
    r""" Compute the mean recall of the nearest neighbor search.
    For each set of neighbors, recall is defined as the number of true/exact
    neighbors returned divided by the number of requested neighbors.
    
    Return: float
    """
    acc = 0.0
    n,k = nbrsExact.shape
    for i in range(n):
        a = nbrsTest[i, :]
        b = nbrsExact[i, :]
        acc += np.intersect1d(a, b).shape[0] / float(k)
        
    return acc / float(n)

def lsh_performance_fun(y_pred,y_test):
    

    LR_acc = metrics.accuracy_score(y_test, y_pred)
    #     print("Logistic Regression Accuracy:",LR_acc)

    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
    #     print("Logistic Regression Precision:",LR_prec)

    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
    #     print("Logistic Regression Recall:",LR_recall)

    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
    #     print("Logistic Regression F1 weighted:",LR_f1_weighted)

    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
    #     print("Logistic Regression F1 macro:",LR_f1_macro)

    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
    #     print("Logistic Regression F1 micro:",LR_f1_micro)

    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# if __name__ == '__main__':
    
# args = get_args()  # command line arguments

lshClasses = {"cos": clsh, "ham": hlsh, "jac": jlsh}

nnbrs = 5

sim = "ham"
ntables = 5
nfunctions = 2

# X, Y = generateSamples(nsamples=nsamples_2, nfeatures=nfeatures_2,
#     binary=False if sim == "cos" else True)

if sim not in lshClasses:
    raise ValueError("Incorrect similarity choice. Try cos, ham, or jac.")
cls = lshClasses[sim] # choose the correct LSH structure

# NO DL TEMP

In [878]:

rkf = RepeatedKFold(n_splits=2, n_repeats=1, random_state=None)
# X is the feature set and y is the target
counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table_no_DL = []
gauu_nb_table_no_DL = []
mlp_table_no_DL = []
knn_table_no_DL = []
rf_table_no_DL = []
lr_table_no_DL = []
lsh_table_no_DL = []

In [879]:

# for train_index, test_index in rkf.split(X):
#  counter = counter+1

 #!!!!!!!!!!!!!!!!!! No DL Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
X_train, X_test, y_train, y_test = train_test_split(
    np.array(data),data_labels,
    test_size=0.3,
    random_state=1,
shuffle=True)
# X_train.shape, X_test.shape
# X_train, X_test = data[train_index], data[test_index]
# y_train, y_test = y[train_index], y[test_index]

svm_return = svm_fun(X_train,y_train,X_test,y_test)
gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
knn_return = knn_fun(X_train,y_train,X_test,y_test)
rf_return = rf_fun(X_train,y_train,X_test,y_test)
lr_return = lr_fun(X_train,y_train,X_test,y_test)

 ################## LSH (start) #######################

# find approximate neighbors using LSH 
t0 = time.time()
L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
T = time.time() - t0

final_LSH_test_labels = []

for i in range(len(y_test)):
    accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
    final_val = statistics.mode(accessed_mapping)
    final_LSH_test_labels.append(final_val)

y_pred = final_LSH_test_labels

final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
check_lsh = np.transpose(final_lsh_computation_cals)
check_lsh
asdd = np.transpose((check_lsh))

#     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

################## LSH (end) ###################

svm_table_no_DL.append(svm_return)
gauu_nb_table_no_DL.append(gauu_nb_return)
mlp_table_no_DL.append(mlp_return)
knn_table_no_DL.append(knn_return)
rf_table_no_DL.append(rf_return)
lr_table_no_DL.append(lr_return)
lsh_table_no_DL.append(asdd)
 #!!!!!!!!!!!!!!!!!! No DL ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#

Confusion Matrix SVM : 
 [[130  79  19  24  26]
 [129  85  30  23  29]
 [142  88  34  29  26]
 [126  87  28  25  24]
 [133  94  31  24  23]]
SVM Class Wise Accuracy :  [0.4676259  0.28716216 0.10658307 0.0862069  0.07540984]
Confusion Matrix NB : 
 [[ 13   6   0  11 248]
 [ 11   6   3   6 270]
 [ 15   7   4   8 285]
 [ 11  13   5   3 258]
 [  8  13   6   9 269]]
NB Class Wise Accuracy :  [0.04676259 0.02027027 0.01253918 0.01034483 0.88196721]
Confusion Matrix MLP : 
 [[ 31  31 167  18  31]
 [ 32  30 191  13  30]
 [ 31  42 195  17  34]
 [ 27  43 184  15  21]
 [ 27  39 196  19  24]]
MLP Class Wise Accuracy :  [0.11151079 0.10135135 0.61128527 0.05172414 0.07868852]
Confusion Matrix KNN : 
 [[147  36  26  24  45]
 [138  37  25  21  75]
 [158  37  41  17  66]
 [156  51  30   9  44]
 [147  43  31  20  64]]
KNN Class Wise Accuracy :  [0.52877698 0.125      0.12852665 0.03103448 0.20983607]
Confusion Matrix RF : 
 [[133  68  21  28  28]
 [112  91  27  23  43]
 [138  74  33  32  42]
 [123  74

In [880]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
print(idx.value_counts())

Here are all of the viral species in the dataset: 
 4958 entries in total
USA        995
Brazil     993
Denmark    992
England    992
Iceland    986
dtype: int64


In [881]:
#!!!!!!!!!! No DL (Start) !!!!!!!!!!!!!#
svm_table_final_no_DL = DataFrame(svm_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final_no_DL = DataFrame(gauu_nb_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final_no_DL = DataFrame(mlp_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final_no_DL = DataFrame(knn_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final_no_DL = DataFrame(rf_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final_no_DL = DataFrame(lr_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lsh_table_final_no_DL = DataFrame(lsh_table_no_DL, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


#taking average of all k-fold performance values
final_mean_mat_no_DL = []

final_mean_mat_no_DL.append(np.transpose((list(svm_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(gauu_nb_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(mlp_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(knn_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(rf_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(lr_table_final_no_DL.mean()))))
final_mean_mat_no_DL.append(np.transpose((list(lsh_table_final_no_DL.mean()))))

final_avg_mat_no_DL = DataFrame(final_mean_mat_no_DL,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

no_DL_result = final_avg_mat_no_DL
no_DL_result

aq = np.array(no_DL_result)
name = result_path + "_random_no_dl_original.csv"
no_DL_result.to_csv(name,index=False)

In [882]:
print(no_DL_result)

     Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.199597   0.202990  0.199597       0.175053    0.176921    0.199597   
NB   0.198253   0.173298  0.198253       0.097569    0.096742    0.198253   
MLP  0.198253   0.186987  0.198253       0.156612    0.154058    0.198253   
KNN  0.200269   0.194238  0.200269       0.173333    0.173954    0.200269   
RF   0.216398   0.215302  0.216398       0.194421    0.196493    0.216398   
LR   0.209677   0.216796  0.209677       0.190760    0.192825    0.209677   
LSH  0.214382   0.223593  0.214382       0.201138    0.201017    0.214382   

      ROC AUC  
SVM  0.502841  
NB   0.496475  
MLP  0.494254  
KNN  0.502936  
RF   0.513296  
LR   0.509004  
LSH  0.509388  


# LASSO Ridge regression for feature selection

In [883]:
# print("Lasso Regression Start!!!")
# scaler = StandardScaler()
# scaler.fit(X_train.fillna(0))

In [884]:
# # L1 = Lasso, L2 = Ridge
# sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l2', solver='liblinear'))
# sel_.fit(scaler.transform(X_train.fillna(0)), y_train)

# sel_.get_support()

In [885]:
# selected_feat = X_train.columns[(sel_.get_support())]
# print('total features: {}'.format((X_train.shape[1])))
# print('selected features: {}'.format(len(selected_feat)))
# print('features with coefficients shrank to zero: {}'.format(
#       np.sum(sel_.estimator_.coef_ == 0)))

In [886]:
# X_train_selected = sel_.transform(X_train.fillna(0))
# X_test_selected = sel_.transform(X_test.fillna(0))
# X_train_selected.shape, X_test_selected.shape

In [887]:
# X_train = X_train_selected
# X_test = X_test_selected

# # X_train = X_train_encoder
# # X_test = X_test_encoder


# k-fold cross validation

In [888]:
# print("k-fold start!!!")

# data_selected = sel_.transform(data.fillna(0)) # For Lasso and Ridge
# # data_selected = data_with_svd #for PCA

In [889]:
# data_selected_ridge = data_selected

# Autoencoder Starts Here

In [890]:
# print("Autoencoder Start!!!")
# X_train, X_test, y_train, y_test = train_test_split(
#     data,data_labels,
#     test_size=0.3,
#     random_state=0)
# X_train.shape, X_test.shape

In [891]:
# from hyperopt import Trials, STATUS_OK, tpe
# from keras.datasets import mnist
# from keras.layers.core import Dense, Dropout, Activation
# from keras.models import Sequential
# from keras.utils import np_utils

# from tensorflow.keras.models import Model, Sequential
# from tensorflow.keras.layers import Conv2D, MaxPooling2D, UpSampling2D, Dropout, Flatten, Dense, Reshape

# from keras.layers import Input,Dense


In [892]:
# # reduce to 20 features
# encoding_dim = 200

# orig_shape = len(X_train.columns)
# input_df = Input(shape=(orig_shape,))
# encoded = Dense(encoding_dim, activation='relu')(input_df)
# decoded = Dense(orig_shape, activation='sigmoid')(encoded)

# # encoder
# autoencoder = Model(input_df, decoded)

# # intermediate result
# encoder = Model(input_df, encoded)

# autoencoder.compile(optimizer='adadelta', loss='mean_squared_error')

# autoencoder.fit(X_train, X_train,
#                 epochs=20,
#                 batch_size=256,
#                 shuffle=True,
#                 validation_data=(X_test, X_test))

In [893]:
# # X_train_encoder = encoder.predict(X_train)
# # X_test_encoder = encoder.predict(X_test)

# # X_train = X_train_encoder
# # X_test = X_test_encoder

# auto_encoder_data = encoder.predict(data)

In [894]:
# auto_encoder_data.shape

# PCA

In [895]:
# print("PCA Start!!!")
# svd = TruncatedSVD(n_components = 50, n_iter = 7, random_state = 42)
# X_50 = svd.fit_transform(data)

# The Johnson-Lindenstrauss lemma Gaussian random projection

In [896]:
# print("JLL Start!!!")
# from sklearn import random_projection

# transformer = random_projection.GaussianRandomProjection()
# data_random_projection = transformer.fit_transform(data)
# data_random_projection.shape


# No Dimensionality Reduction

In [897]:
# X_train_no_dl, X_test_no_dl, y_train_no_dl, y_test_no_dl = train_test_split(
#     np.array(data),data_labels,
#     test_size=0.3,
#     random_state=0)
# X_train_no_dl.shape, X_test_no_dl.shape

In [898]:
# y =  np.array(data_labels)


# X_ridge = data_selected_ridge
# X_auto_encoder = auto_encoder_data
# X_PCA = X_50
# X_JLL = data_random_projection



# rkf = RepeatedKFold(n_splits=2, n_repeats=1, random_state=None)
# # X is the feature set and y is the target
# counter = 1
# # print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
# svm_table_no_DL = []
# gauu_nb_table_no_DL = []
# mlp_table_no_DL = []
# knn_table_no_DL = []
# rf_table_no_DL = []
# lr_table_no_DL = []
# lsh_table_no_DL = []

# svm_table_ridge = []
# gauu_nb_table_ridge = []
# mlp_table_ridge = []
# knn_table_ridge = []
# rf_table_ridge = []
# lr_table_ridge = []
# lsh_table_ridge = []

# svm_table_auto_encoder = []
# gauu_nb_table_auto_encoder = []
# mlp_table_auto_encoder = []
# knn_table_auto_encoder = []
# rf_table_auto_encoder = []
# lr_table_auto_encoder = []
# lsh_table_auto_encoder = []

# svm_table_PCA = []
# gauu_nb_table_PCA = []
# mlp_table_PCA = []
# knn_table_PCA = []
# rf_table_PCA = []
# lr_table_PCA = []
# lsh_table_PCA = []

# svm_table_JLL = []
# gauu_nb_table_JLL = []
# mlp_table_JLL = []
# knn_table_JLL = []
# rf_table_JLL = []
# lr_table_JLL = []
# lsh_table_JLL = []

In [899]:
# data.shape

In [900]:
# X_train, X_test, y_train, y_test = train_test_split(
#     np.array(data),data_labels,
#     test_size=0.3,
#     random_state=1,
# shuffle=True)
# X_train.shape, X_test.shape

In [901]:

# # for train_index, test_index in rkf.split(X):
# #  counter = counter+1

#  #!!!!!!!!!!!!!!!!!! No DL Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# X_train, X_test, y_train, y_test = train_test_split(
#     np.array(data),data_labels,
#     test_size=0.3,
#     random_state=1,
# shuffle=True)
# # X_train.shape, X_test.shape
# # X_train, X_test = data[train_index], data[test_index]
# # y_train, y_test = y[train_index], y[test_index]

# svm_return = svm_fun(X_train,y_train,X_test,y_test)
# gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# knn_return = knn_fun(X_train,y_train,X_test,y_test)
# rf_return = rf_fun(X_train,y_train,X_test,y_test)
# lr_return = lr_fun(X_train,y_train,X_test,y_test)

#  ################## LSH (start) #######################

# # find approximate neighbors using LSH 
# t0 = time.time()
# L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
# nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
# T = time.time() - t0

# final_LSH_test_labels = []

# for i in range(len(y_test)):
#     accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
#     final_val = statistics.mode(accessed_mapping)
#     final_LSH_test_labels.append(final_val)

# y_pred = final_LSH_test_labels

# final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
# check_lsh = np.transpose(final_lsh_computation_cals)
# check_lsh
# asdd = np.transpose((check_lsh))

# #     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

# ################## LSH (end) ###################

# svm_table_no_DL.append(svm_return)
# gauu_nb_table_no_DL.append(gauu_nb_return)
# mlp_table_no_DL.append(mlp_return)
# knn_table_no_DL.append(knn_return)
# rf_table_no_DL.append(rf_return)
# lr_table_no_DL.append(lr_return)
# lsh_table_no_DL.append(asdd)
#  #!!!!!!!!!!!!!!!!!! No DL ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#






# #  #!!!!!!!!!!!!!!!!!! Ridge Regression Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # X_train, X_test, y_train, y_test = train_test_split(
# #     np.array(X_ridge),data_labels,
# #     test_size=0.3,
# #     random_state=1,
# # shuffle=True)
# # #  X_train, X_test = X_ridge[train_index], X_ridge[test_index]
# # #  y_train, y_test = y[train_index], y[test_index]

# # svm_return = svm_fun(X_train,y_train,X_test,y_test)
# # gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# # mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# # knn_return = knn_fun(X_train,y_train,X_test,y_test)
# # rf_return = rf_fun(X_train,y_train,X_test,y_test)
# # lr_return = lr_fun(X_train,y_train,X_test,y_test)

# #  ################## LSH (start) #######################

# #  # find approximate neighbors using LSH 
# # t0 = time.time()
# # L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
# # nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
# # T = time.time() - t0

# # final_LSH_test_labels = []

# # for i in range(len(y_test)):
# #     accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
# #     final_val = statistics.mode(accessed_mapping)
# #     final_LSH_test_labels.append(final_val)

# # y_pred = final_LSH_test_labels

# # final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
# # check_lsh = np.transpose(final_lsh_computation_cals)
# # check_lsh
# # asdd = np.transpose((check_lsh))

# # #     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

# # ################## LSH (end) ###################

# # svm_table_ridge.append(svm_return)
# # gauu_nb_table_ridge.append(gauu_nb_return)
# # mlp_table_ridge.append(mlp_return)
# # knn_table_ridge.append(knn_return)
# # rf_table_ridge.append(rf_return)
# # lr_table_ridge.append(lr_return)
# # lsh_table_ridge.append(asdd)




# #  #!!!!!!!!!!!!!!!!!! Auto Encoder Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # X_train, X_test, y_train, y_test = train_test_split(
# #     np.array(X_auto_encoder),data_labels,
# #     test_size=0.3,
# #     random_state=1,
# # shuffle=True)

# # #  X_train, X_test = X_auto_encoder[train_index], X_auto_encoder[test_index]
# # #  y_train, y_test = y[train_index], y[test_index]

# # svm_return = svm_fun(X_train,y_train,X_test,y_test)
# # gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# # mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# # knn_return = knn_fun(X_train,y_train,X_test,y_test)
# # rf_return = rf_fun(X_train,y_train,X_test,y_test)
# # lr_return = lr_fun(X_train,y_train,X_test,y_test)

# #  ################## LSH (start) #######################

# # #     X_train, X_test, y_train, y_test = train_test_split(
# # #         np.array(data),data_labels,
# # #         test_size=0.3,
# # #         random_state=0)
# # #     X_train.shape, X_test.shape

# #  # find approximate neighbors using LSH 
# # t0 = time.time()
# # L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
# # nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
# # T = time.time() - t0

# # final_LSH_test_labels = []

# # for i in range(len(y_test)):
# #     accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
# #     final_val = statistics.mode(accessed_mapping)
# #     final_LSH_test_labels.append(final_val)

# # y_pred = final_LSH_test_labels

# # final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
# # check_lsh = np.transpose(final_lsh_computation_cals)
# # check_lsh
# # asdd = np.transpose((check_lsh))

# # #     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

# # ################## LSH (end) ###################

# # svm_table_auto_encoder.append(svm_return)
# # gauu_nb_table_auto_encoder.append(gauu_nb_return)
# # mlp_table_auto_encoder.append(mlp_return)
# # knn_table_auto_encoder.append(knn_return)
# # rf_table_auto_encoder.append(rf_return)
# # lr_table_auto_encoder.append(lr_return)
# # lsh_table_auto_encoder.append(asdd)

# #  #!!!!!!!!!!!!!!!!!! Auto Encoder Ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#

    
    
    
    
# #  #!!!!!!!!!!!!!!!!!! PCA Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # X_train, X_test, y_train, y_test = train_test_split(
# #     np.array(X_PCA),data_labels,
# #     test_size=0.3,
# #     random_state=1,
# # shuffle=True)

# # #  X_train, X_test = X_PCA[train_index], X_PCA[test_index]
# # #  y_train, y_test = y[train_index], y[test_index]

# # svm_return = svm_fun(X_train,y_train,X_test,y_test)
# # gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# # mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# # knn_return = knn_fun(X_train,y_train,X_test,y_test)
# # rf_return = rf_fun(X_train,y_train,X_test,y_test)
# # lr_return = lr_fun(X_train,y_train,X_test,y_test)

# # ################## LSH (start) #######################

# # # find approximate neighbors using LSH 
# # t0 = time.time()
# # L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
# # nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
# # T = time.time() - t0

# # final_LSH_test_labels = []

# # for i in range(len(y_test)):
# #     accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
# #     final_val = statistics.mode(accessed_mapping)
# #     final_LSH_test_labels.append(final_val)

# # y_pred = final_LSH_test_labels

# # final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
# # check_lsh = np.transpose(final_lsh_computation_cals)
# # check_lsh
# # asdd = np.transpose((check_lsh))

# # #     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

# # ################## LSH (end) ###################

# # svm_table_PCA.append(svm_return)
# # gauu_nb_table_PCA.append(gauu_nb_return)
# # mlp_table_PCA.append(mlp_return)
# # knn_table_PCA.append(knn_return)
# # rf_table_PCA.append(rf_return)
# # lr_table_PCA.append(lr_return)
# # lsh_table_PCA.append(asdd)  
# #  #!!!!!!!!!!!!!!!!!! PCA Ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#

    
    
# #  #!!!!!!!!!!!!!!!!!! JLL Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # X_train, X_test, y_train, y_test = train_test_split(
# #     np.array(X_JLL),data_labels,
# #     test_size=0.3,
# #     random_state=1,
# # shuffle=True)

# # #  X_train, X_test = X_JLL[train_index], X_JLL[test_index]
# # #  y_train, y_test = y[train_index], y[test_index]

# # svm_return = svm_fun(X_train,y_train,X_test,y_test)
# # gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
# # mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
# # knn_return = knn_fun(X_train,y_train,X_test,y_test)
# # rf_return = rf_fun(X_train,y_train,X_test,y_test)
# # lr_return = lr_fun(X_train,y_train,X_test,y_test)

# # ################## LSH (start) #######################

# # #     X_train, X_test, y_train, y_test = train_test_split(
# # #         np.array(data),data_labels,
# # #         test_size=0.3,
# # #         random_state=0)
# # #     X_train.shape, X_test.shape

# # # find approximate neighbors using LSH 
# # t0 = time.time()
# # L = cls(X_train, ntables=ntables, nfunctions=nfunctions)
# # nbrsTest  = L.findNeighbors(X_test, k=nnbrs)
# # T = time.time() - t0

# # final_LSH_test_labels = []

# # for i in range(len(y_test)):
# #     accessed_mapping = list(map(y_train.__getitem__, nbrsTest[i]))
# #     final_val = statistics.mode(accessed_mapping)
# #     final_LSH_test_labels.append(final_val)

# # y_pred = final_LSH_test_labels

# # final_lsh_computation_cals = lsh_performance_fun(y_pred,y_test)
# # check_lsh = np.transpose(final_lsh_computation_cals)
# # check_lsh
# # asdd = np.transpose((check_lsh))

# # #     asdd.columns =["Accuracy","Precision","Recall","F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"]

# # ################## LSH (end) ###################

# # svm_table_JLL.append(svm_return)
# # gauu_nb_table_JLL.append(gauu_nb_return)
# # mlp_table_JLL.append(mlp_return)
# # knn_table_JLL.append(knn_return)
# # rf_table_JLL.append(rf_return)
# # lr_table_JLL.append(lr_return)
# # lsh_table_JLL.append(asdd)  
# #  #!!!!!!!!!!!!!!!!!! JLL Ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#




In [902]:
# #!!!!!!!!!! No DL (Start) !!!!!!!!!!!!!#
# svm_table_final_no_DL = DataFrame(svm_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# gauu_nb_table_final_no_DL = DataFrame(gauu_nb_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# mlp_table_final_no_DL = DataFrame(mlp_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# knn_table_final_no_DL = DataFrame(knn_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# rf_table_final_no_DL = DataFrame(rf_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# lr_table_final_no_DL = DataFrame(lr_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# lsh_table_final_no_DL = DataFrame(lsh_table_no_DL, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


# #taking average of all k-fold performance values
# final_mean_mat_no_DL = []

# final_mean_mat_no_DL.append(np.transpose((list(svm_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(gauu_nb_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(mlp_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(knn_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(rf_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(lr_table_final_no_DL.mean()))))
# final_mean_mat_no_DL.append(np.transpose((list(lsh_table_final_no_DL.mean()))))

# final_avg_mat_no_DL = DataFrame(final_mean_mat_no_DL,columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
#                           index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

# no_DL_result = final_avg_mat_no_DL
# no_DL_result

# aq = np.array(no_DL_result)
# name = result_path + "_random_no_dl_original.csv"
# no_DL_result.to_csv(name,index=False)


# # #!!!!!!!!!! Ridge (Start) !!!!!!!!!!!!!#
# # svm_table_final_ridge = DataFrame(svm_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # gauu_nb_table_final_ridge = DataFrame(gauu_nb_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # mlp_table_final_ridge = DataFrame(mlp_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # knn_table_final_ridge = DataFrame(knn_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # rf_table_final_ridge = DataFrame(rf_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lr_table_final_ridge = DataFrame(lr_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lsh_table_final_ridge = DataFrame(lsh_table_ridge, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


# # #taking average of all k-fold performance values
# # final_mean_mat_ridge = []

# # final_mean_mat_ridge.append(np.transpose((list(svm_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(gauu_nb_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(mlp_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(knn_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(rf_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(lr_table_final_ridge.mean()))))
# # final_mean_mat_ridge.append(np.transpose((list(lsh_table_final_ridge.mean()))))

# # final_avg_mat_ridge = DataFrame(final_mean_mat_ridge,columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
# #                           index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

# # ridge_result = final_avg_mat_ridge
# # ridge_result

# # aq = np.array(ridge_result)
# # name = result_path + "_random_ridge_original.csv"
# # ridge_result.to_csv(name,index=False)

# # #!!!!!!!!!! Auto Encoder (Start) !!!!!!!!!!!!!#
# # svm_table_final_auto_encoder = DataFrame(svm_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # gauu_nb_table_final_auto_encoder = DataFrame(gauu_nb_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # mlp_table_final_auto_encoder = DataFrame(mlp_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # knn_table_final_auto_encoder = DataFrame(knn_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # rf_table_final_auto_encoder = DataFrame(rf_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lr_table_final_auto_encoder = DataFrame(lr_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lsh_table_final_auto_encoder = DataFrame(lsh_table_auto_encoder, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


# # #taking average of all k-fold performance values
# # final_mean_mat_auto_encoder = []

# # final_mean_mat_auto_encoder.append(np.transpose((list(svm_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(gauu_nb_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(mlp_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(knn_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(rf_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(lr_table_final_auto_encoder.mean()))))
# # final_mean_mat_auto_encoder.append(np.transpose((list(lsh_table_final_auto_encoder.mean()))))


# # final_avg_mat_auto_encoder = DataFrame(final_mean_mat_auto_encoder,columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
# #                           index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

# # auto_encoder_result = final_avg_mat_auto_encoder
# # auto_encoder_result

# # name = result_path + "_random_autoencoder_original.csv"
# # auto_encoder_result.to_csv(name,index=False)

# # #!!!!!!!!!! Auto Encoder (ends) !!!!!!!!!!!!!#


# #  #!!!!!!!!!!!!!!!!!! PCA Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # svm_table_final_PCA = DataFrame(svm_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # gauu_nb_table_final_PCA = DataFrame(gauu_nb_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # mlp_table_final_PCA = DataFrame(mlp_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # knn_table_final_PCA = DataFrame(knn_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # rf_table_final_PCA = DataFrame(rf_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lr_table_final_PCA = DataFrame(lr_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lsh_table_final_PCA = DataFrame(lsh_table_PCA, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

# # #taking average of all k-fold performance values
# # final_mean_mat_PCA = []

# # final_mean_mat_PCA.append(np.transpose((list(svm_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(gauu_nb_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(mlp_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(knn_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(rf_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(lr_table_final_PCA.mean()))))
# # final_mean_mat_PCA.append(np.transpose((list(lsh_table_final_PCA.mean()))))


# # final_avg_mat_PCA = DataFrame(final_mean_mat_PCA,columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
# #                           index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

# # PCA_result = final_avg_mat_PCA
# # PCA_result

# # name = result_path + "_random_PCA_original.csv"
# # PCA_result.to_csv(name,index=False)
# #  #!!!!!!!!!!!!!!!!!! PCA Ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#

# #  #!!!!!!!!!!!!!!!!!! JLL Starts Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# # svm_table_final_JLL = DataFrame(svm_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # gauu_nb_table_final_JLL = DataFrame(gauu_nb_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # mlp_table_final_JLL = DataFrame(mlp_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # knn_table_final_JLL = DataFrame(knn_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # rf_table_final_JLL = DataFrame(rf_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lr_table_final_JLL = DataFrame(lr_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
# # lsh_table_final_JLL = DataFrame(lsh_table_JLL, columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

# # #taking average of all k-fold performance values
# # final_mean_mat_JLL = []

# # final_mean_mat_JLL.append(np.transpose((list(svm_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(gauu_nb_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(mlp_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(knn_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(rf_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(lr_table_final_JLL.mean()))))
# # final_mean_mat_JLL.append(np.transpose((list(lsh_table_final_JLL.mean()))))


# # final_avg_mat_JLL = DataFrame(final_mean_mat_JLL,columns=["Accuracy","Precision","Recall",
# #                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
# #                           index=["SVM","NB","MLP","KNN","RF","LR","LSH"])

# # JLL_result = final_avg_mat_JLL
# # JLL_result

# # name = result_path + "_random_JLL_Gaussian_random_projection_original.csv"
# # JLL_result.to_csv(name,index=False)
# #  #!!!!!!!!!!!!!!!!!! JLL Ends Here !!!!!!!!!!!!!!!!!!!!!!!!!!!!#

In [903]:
# print(no_DL_result)
# print(ridge_result)
# print(PCA_result)
# print(auto_encoder_result)
# print(JLL_result)

In [904]:
idx = pd.Index(cities) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
print(idx.value_counts())

Here are all of the viral species in the dataset: 
 4958 entries in total
USA        995
Brazil     993
Denmark    992
England    992
Iceland    986
dtype: int64


# LSTM Model

In [905]:
# import numpy
# import matplotlib.pyplot as plt
# import pandas
# import math
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.layers import LSTM
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.metrics import mean_squared_error

# # LSTM for sequence classification in the IMDB dataset
# import numpy
# from keras.datasets import imdb
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.layers import LSTM
# from keras.layers.embeddings import Embedding
# from keras.preprocessing import sequence

# from keras.callbacks import ModelCheckpoint, EarlyStopping
# from keras.preprocessing.sequence import pad_sequences


In [906]:
# np.unique(data_labels)

In [907]:
# # string to int labels
# unique_names = np.unique(data_labels)
# # creating a dict file 
# str_to_int_values = {'Sweden': 1,'UK': 2,'USA': 3}
  
# # traversing through dataframe
# # Gender column and writing
# # values where key matches
# data_labels_int = [str_to_int_values[item] for item in data_labels]

In [908]:
# data.shape

In [909]:
# # X = tokenizer.texts_to_sequences(df['Consumer complaint narrative'].values)
# MAX_SEQUENCE_LENGTH = 250
# X = pad_sequences(np.array(data), maxlen=MAX_SEQUENCE_LENGTH)
# print('Shape of data tensor:', X.shape)

In [910]:
# X_train, X_test, Y_train, Y_test = train_test_split(
#     data,data_labels_int, 
#     test_size = 0.10, 
#     random_state = 42)
# # print(X_train.shape,Y_train.shape)
# # print(X_test.shape,Y_test.shape)
# X_train.shape, X_test.shape

In [911]:
# # https://towardsdatascience.com/multi-class-text-classification-with-lstm-1590bee1bd17
# aaa = (X_train.shape)
# MAX_NB_WORDS = aaa[1]
# EMBEDDING_DIM = 100

# model = Sequential()
# model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=data.shape[1]))
# # model.add(SpatialDropout1D(0.2))
# model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
# model.add(Dense(1, activation='softmax'))
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# epochs = 5
# batch_size = 64

# # history = model.fit((X_train), np.array(Y_train), epochs=32, batch_size=40,validation_split=0.1)
# history = model.fit(X_train, np.array(Y_train), epochs=epochs, batch_size=batch_size,validation_split=0.1,callbacks=[EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])


In [912]:
# accr = model.evaluate(X_test,Y_test)
# print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

In [913]:
# plt.title('Loss')
# plt.plot(history.history['loss'], label='train')
# plt.plot(history.history['val_loss'], label='test')
# plt.legend()
# plt.show();

In [914]:
# plt.title('Accuracy')
# plt.plot(history.history['acc'], label='train')
# plt.plot(history.history['val_acc'], label='test')
# plt.legend()
# plt.show();